### ISSUE TITLE
can we send report as stream to front end? how?

### ISSUE THREAD

**Issue by Naliniamu** [NathanaelA/fluentreports#100]
i want to send my report to browser and display over the browser. how to send. i can make a reports as pdf file only. and how to use pipe stream

**Comment by NathanaelA** [comment]
The reporting engine always generates a PDF -- you can generate the PDF on the browser or on the  server.

**Comment by Naliniamu** [comment]
How to send buffer type report to client side

**Comment by NathanaelA** [comment]
1. You output to either pipe or buffer.
2. You send the content type for pdf
3. You output your buffer or pipe to the open http connection.

I'll try and work up a sample in the next release.
