### ISSUE TITLE
[FRG] - Implement custom fonts

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#102]
We use this type of functionality to import and use MICR fonts, or condensed fonts for data-dense reports.

**Comment by NathanaelA** [comment]
Should this be where we allow you to add fonts and font path to the fRG, so they show up in the fonts list.   Or where the user would upload a font to be base64 encoded in the json?

**Comment by NathanaelA** [comment]
Added to the engine.
