### ISSUE TITLE
[FRG] - Identify a way to generate dynamic bands

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#104]
We often require that reports have a dynamic number of band columns. Many times we have a generic report that can be customized based on settings or user preferences. It would be nice to figure out a way to have a dynamic number of columns.

Along with that there are also many times when we want the band to span a certain width, like the width of the report, and we just want each column to take up a percentage of that available width.

**Comment by NathanaelA** [comment]
The ability for the report engine to have a function on the number of columns should be trivial; but I'm not following the use case....   The browse reports are dynamically created from code, so they shouldn't need an editor on them.

So you might have to describe the use case, so I can understand why; because is their a report that would have a variable number of columns that would need to be editable.

**Comment by beaudesigns** [comment]
I think I see what you're saying. In other words, you could either generate the report structure JSON completely through code, or use the visual editor to generate the skeleton, like the title header. Then generate the band header/footer/detail through code.

There are a few use cases:
- A generic "browse" dataset report. A single report that can be used to print a simple data-list from basically any dataset. Each dataset would have a unique number of columns and rows, but they visually look the same all the time.
- A generic "record" report. A list of all of the available fields for that record is used to generate a data sheet based on that record.
- Reports that allow for user, or customer defined options to show or hide columns.

I think basically all of those can be managed how you're saying, where you just manually create or modify the JSON. The only feature I can think of that might be nice on top of that, is a way to dynamically set the width. There's a couple of options.
- Add a way to set a column as a percentage width, instead of a fixed value
- Expose a way to get the total report width

A common pattern that we _currently_ use is this:
```
const cellWidth = (report.maxX() - report.minX()) / 10;
report.band({
  {data: 'First', width: cellWidth * 2},
  {data: 'Second', width: cellWidth * 5},
  {data: 'Third', width: cellWidth * 3},
})
```

This allows us to create a "grid" that we can use to lay out the report. That way the grid and columns scale no matter what the paper size is, or the paper orientation, etc.

A couple of examples of the generic reports:
[generic-record.pdf](https://github.com/NathanaelA/fluentreports/files/3789263/generic-record.pdf)
[generic-dataset.pdf](https://github.com/NathanaelA/fluentreports/files/3789264/generic-dataset.pdf)

**Comment by NathanaelA** [comment]
Ok, I have done a couple things to solve this issue.   :-D  

1st. I have created two new `report` functions; report.pageWidth() and report.pageHeight(); these are the actual printable area (i.e. page size - margins).   

I have also exposed the ability for band width's to be a function.  :-)

So now, in my test I used as the band function for the column with `return report.pageWidth()/10*4;`    This would be the same equivalent as your `cellWidth * 4`   

Do you believe these items all together would solve the issues you believe you might see?

**Comment by beaudesigns** [comment]
Yes! I think that definitely gives us the functionality that we need in most cases.

Now that you have those functions, how hard would it be to support percentage widths as well as absolute widths? That feature would make most reporting way simpler, and save us having to do function band widths everywhere. Basically taking the common pattern of figuring out the percentage to use as the width, and just doing it as part of the reporting engine.

It's not a deal breaker, but I could see that being a huge QoL improvement.

**Comment by NathanaelA** [comment]
All the `width` fields should now support percentages.   Please let me know if you find a width that doesn't but all of them should.   
If you pass in `33%` you will get 1/3 of the printable width.    Anything else that you think would make life easier.

**Comment by beaudesigns** [comment]
I just tested the percentage width for band cells, and it works perfectly. This is going to be a _huge_ upgrade to our report building flow. Thank you Nathanael!
