### ISSUE TITLE
FluentReportsGenerator: Add a way to print the page number on each page

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#105]
The page number is the big need. "Page X/X". It would be nice to be able to print other things as part of that, like the date and time it was printed. Even something generic like adding a "marginText" object or something like that.

**Comment by NathanaelA** [comment]
The engine already supports that -- I think I forgot to export it.  But I'll make sure it is accessable in the next version.

**Comment by NathanaelA** [comment]
This has been exposed as a new element on the toolbar.
