### ISSUE TITLE
[FRG] - Support images

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#107]
For standardized forms, logos, stamps, signatures, etc, we print images on the PDF.

Part of me wonders if it would be possible to store the images in base64 as part of the report definition JSON. There's pros and cons to that.

**Comment by NathanaelA** [comment]
We could do both a url to the image; a data-field to the image; or base-64.   I was thinking of having it support all three; but wanted to make sure I understood the use-case so that we could get it working the best possible way since this is typically an external resource...

**Comment by beaudesigns** [comment]
As we're talking through some of these, we're finding a consistent theme of wanting the ability to store report assets in the report JSON. Assets would be things like report background images, logos, "stamps", or digital signatures stored as images.

If they were embedded in the JSON as Base64, I think that'd also make it very easy to show those in the report editor in the browser. That would make report creation much easier, especially when you have the use case of starting with a base report image as the background, and then you're just dragging and dropping to fill in the data.

All that to say, there aren't any use cases that I know of that wouldn't be solved by storing the images, or report assets, as base64 in the report structure JSON.

**Comment by NathanaelA** [comment]
Added to current version.
