### ISSUE TITLE
FluentReportsGenerator: Add an option to override "Preview" button

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#110]
I'd like to be able to pass in an option to override the action that happens when the preview button is clicked. In my case, I want to:
- Trigger the save action on the report
- Emit an event from my component to our engine
- Render and show my own preview

**Comment by NathanaelA** [comment]
The new version now allows you to pass in a "preview" option with a function that gets
`function (reportgenerator, doneCallback)`
  You can then do whatever you want in that callback.   When you are all done, just call the doneCallback and the editor will resume...

Some additional enhancements to deal with the above requests:
```
  const currentReport = reportGenerator.report` to get the current report
  const currentData = reportGenerator.data` to get the current data.
``` 

You can also call a new `preview(options)` function which will create the entire preview in whatever parent element you want to display it in, so you don't have to code it unless you want to.   I just refactored the code to allow a optional `options.parent` to be passed in to change wherever you want it place on...

// You can optionally pass in currentReport, and currentData, if you don't set them, they will use the reports current versions.    
Example:
`reportGenerator.preview({parent: someparentelement, report: currentReport, data: currentData});`
