### ISSUE TITLE
[FRG] - Expose a "Set Config" method

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#113]
With our application, configuration settings can be applied after a FRG instance is initialized. I can usually manually set whatever `this._foo` internal variable I need to, but it would be nice to have a consistent API to set configuration options after the fact. Something like:

```
const previewFunction = () => {};
const fluentReports = new FluentReportsGenerator({});
fluentReports.setConfig('preview', previewFunction);
```

**Comment by NathanaelA** [comment]
setConfig has been added to the next version. :grinning:
