### ISSUE TITLE
[FRG] - Unknown text in _parseSection

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#114]
Every time I initialize an editor, I get an error
> Unknown text in _parseSection

The `data` parameter for `_parseSection()` is
```
{type: "text", text: "Welcome to fluentReports"}
```

The default is to throw an error, but I'm wondering if that make sense in general. One thing great about the JSON structure, is that developers could potentially store and retrieve other types of data along with the report, making it a very portable and flexible format.

The error is non-blocking, but may not be needed at all. Ignoring unknown types is probably fine, IMO.

**Comment by NathanaelA** [comment]
Maybe this warning could be set to be enabled while in debug mode.  The whole purpose for the error is to make sure that I wasn't creating an invalid structure for diagnostic purposes..  :grinning:

**Comment by beaudesigns** [comment]
That works too! 👍

**Comment by NathanaelA** [comment]
These messages have now been filtered out if you haven't set a `options.debug = true` when creating the resport.
