### ISSUE TITLE
[FRG] - Expose margins setting

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#115]
It looks like there is a way to pass in margins, but I am not seeing a way in the visual builder to set the margins on a report.

**Comment by NathanaelA** [comment]
Fixed in next version.

**Comment by beaudesigns** [comment]
@NathanaelA This might need to be re-opened. It looks like the margins get saved as a string in the JSON, and then that is passed to PDFKit. 

If I set all of the margin values, I get:
> Error: unsupported number: NaN

If values get mixed, you end up with something like
> Error: unsupported number: 40117.04005.867999999999999

**Comment by NathanaelA** [comment]
Good catch, this is now fixed in the current version.
