### ISSUE TITLE
[FRG] - Confusing section and object placement

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#116]
I wrote a simple, dynamically generated report to begin testing the reporting capabilities. It's a simple report that lists out some of the hotkeys available in our application. I then fed the generated JSON and data into the report editor to see what it'd look like.

What I've found, is that the object placement, and the sections they go in are either just confusing, or maybe wrong. I'm not sure at this point if it's a bug, or just me misunderstanding it.

I've attached the simple test: [reportgenerator.html.txt](https://github.com/NathanaelA/fluentreports/files/3860319/reportgenerator.html.txt) (renamed to .txt for Github)

In the screenshot:
- The "name" data field, which prints the hotkey section group name, looks like it's part of the Title Header section, not the group header section.
- Same with the band. It looks like it's under the header, and not part of the detail for that.
- The "New/Blank" line is actually on the Name group footer.

The same with the band line. 
![Screen Shot 2019-11-18 at 1 33 50 PM](https://user-images.githubusercontent.com/193887/69083666-2f6e5f00-0a08-11ea-9eff-fe692d45b193.png)

It feels like everything is shifted by one, but maybe I'm just misunderstanding it.

**Comment by NathanaelA** [comment]
I can understand what you are saying --    The label is currently at the bottom of the section because it is used as a handle to increase/ decrease that sections size.

One idea I had to actually put an additional label  here:
![image](https://user-images.githubusercontent.com/850871/69100981-065bc780-0a24-11ea-9987-05f1b3ba364d.png)
So that it is a little bit easier to understand the sections...     

Thoughts?

**Comment by beaudesigns** [comment]
That's a possibility, but I think it still leaves some room for confusion.

I'm automatically interpreting those as headers for their section. So the structure I'd expect is probably:

```
Section Header Label
-------
Bands/text/objects/etc
…
…
-------
```

On the last line, I intuitively want to be able to drag the entire dashed line to resize the section above it. If any of that makes sense.

So in a nutshell, I think my best suggestion would be to move the section header label to the top of each section. Don't use it as a handle, but just as a click & edit for the section. And then used the dashed bottom-border as the handle.

I realize that'd be a fairly big deviation from how it's designed currently, and there are some challenges, like putting the section header at the top, but still being able to put report objects at the top of a section.

Now that I know how it works, I can understand it, but my only concern is that I think most people who are learning to use it will go through similar confusion.

Here's a super rough mockup of how that might look.
![Screen Shot 2019-11-19 at 9 01 10 AM](https://user-images.githubusercontent.com/193887/69157870-2e423e00-0aab-11ea-9e4a-a7595e17591f.png)

**Comment by NathanaelA** [comment]
Actually this change isn't that hard -- Just like I do with the field titles; I can easily move the title to the top.   The lines could actually be the handle; just means a little bit smaller area to grab...   

If this is your preference; I'll see what I can do.  :grinning:

**Comment by beaudesigns** [comment]
So after some discussion on our end, what do you think about this idea?

![Screen Shot 2019-11-19 at 4 56 48 PM](https://user-images.githubusercontent.com/193887/69193990-a7fb1b80-0aed-11ea-8771-81c7f967556a.png)

- Make the section headers fully opaque
- Move them to the top of the section
- Make them full-width and centered text
- Make the header a handle for resizing the section above it

The last one is the only potentially tricky one that I can think of. That one seems a little bit weird, but I think when you're designing a report, it'll make good sense.

What are your thoughts on that idea?

**Comment by NathanaelA** [comment]
I think we can make that work.   And it does make sense.    I'll try and get that into the next version...

**Comment by NathanaelA** [comment]
Fixed in current version.
