### ISSUE TITLE
[FRG] - Print Dynamic Data broken

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#117]
It looks like The "Print dynamic data" button might be broken. I click on it, and get a "variable/unset" key value added, but when I try to click on that to edit it, I get some errors.

> Uncaught TypeError: this.createDataSelect is not a function
>     at frPrintDynamic._generateDataFieldSelection (fluentReportsGenerator.js:3346)
>     at UI._handleShowProperty (fluentReportsGenerator.js:5742)
>     at UI._handleShowProperties (fluentReportsGenerator.js:5672)
>     at UI.showProperties (fluentReportsGenerator.js:5628)
>     at FluentReportsGenerator.showProperties (fluentReportsGenerator.js:1223)
>     at frPrintDynamic._selected (fluentReportsGenerator.js:2351)
>     at frPrintDynamic._mouseDown (fluentReportsGenerator.js:2311)

**Comment by NathanaelA** [comment]
Ah, thanks you are correct I broke that control in the UI refactoring.    It is fixed in the next version.
