### ISSUE TITLE
[FRG] - Setting band cell alignment doesn't work

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#119]
When I tried to set the alignment of a band cell to centered, it stayed left aligned. The JSON that it generates looks like this:

```
{"type":"band","fields":[{"text":"Keli Keyboard Shortcuts","type":"text","align":"2","width":"100%"}],"settings":{"align":0}}
```

It's possible that the same issue that margins have is seen here as well, where "2" is a string? It's possible that other places have that same issue as well, but I haven't checked.

**Comment by NathanaelA** [comment]
You are correct, that is supposed to be a number -- the generator has been updated to make sure this is now a number.   In addition the band should also re-show left align if you had a different alignment set before.   Thanks!
