### ISSUE TITLE
[FRG] - Saving after adding "Print Label" doesn't work

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#120]
When I try to add a "Print Label" field, the JSON that it generates, when passed back into the report builder, doesn't seem to be valid. I end up with

> Uncaught TypeError: Cannot read property '_parseElement' of undefined
>     at frSection._parseSection (fluentReportsGenerator.js:1547)
>     at FluentReportsGenerator._generateSection (fluentReportsGenerator.js:1241)
>     at FluentReportsGenerator._generateReportFooterSectionLayout (fluentReportsGenerator.js:1192)
>     at FluentReportsGenerator._generateReportFooterSectionLayout (fluentReportsGenerator.js:1188)
>     at FluentReportsGenerator._generateReportLayout (fluentReportsGenerator.js:1215)
>     at FluentReportsGenerator._parseReport (fluentReportsGenerator.js:481)

Here is the JSON that gets generated.
```
{"type":"report","dataSet":0,"fontSize":8,"autoPrint":false,"name":"keli-keyboard-shortcuts.pdf","paperSize":"letter","paperOrientation":"portrait","margins":{"left":40,"top":40,"right":40,"bottom":40},"fonts":[],"variables":{},"titleHeader":[{"settings":{"align":0},"type":"band","fields":[{"text":"Keli Keyboard Shortcuts","type":"text","align":"2","width":"100%"}]},{"label":"Label","settings":{"addY":19,"align":0},"type":"print"}],"groupBy":[{"type":"group","groupOn":"name","header":[{"field":"name","settings":{"fontBold":true,"align":"center"},"type":"print"}],"footer":[{"thickness":1,"type":"bandLine"},{"type":"newLine"}]}],"subReport":{"type":"report","detail":[{"settings":{"align":0,"wrap":true},"type":"band","fields":[{"align":3,"field":"keys1","width":"22%"},{"align":2,"width":"3%","function":{"name":"Band Function","type":"function","async":false,"function":"return (data.keys1 ? `:` : ``)"}},{"field":"help1","width":"25%"},{"align":3,"field":"keys2","width":"22%"},{"align":2,"width":"3%","function":{"name":"Band Function","type":"function","async":false,"function":"return (data.keys2 ? `:` : ``)"}},{"field":"help2","width":"25%"}]}],"dataType":"parent","data":"hotkeys","dataSet":1}}
```

**Comment by NathanaelA** [comment]
Thanks for the report; it was saving it to the wrong variable name.   Fixed.
