### ISSUE TITLE
[FRG] - Expose a way to set the report data in the editor

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#123]
This is more of a feature request, but I am needing a way to update, or set the JSON data rows inside of the report editor. So the scenario would be:

- Create a new "blank" report
- Click the "Edit report dataset" action
- Paste in my JSON into a field.

If that becomes available, I think that the report data rows would also need to be included in the custom `save()` function that can be specified on the report configuration when you do a `new FluentReportsGenerator()`, so that the new data can be saved back to the database.

I hope that makes sense, please let me know if you need any clarification.

**Comment by NathanaelA** [comment]
This ability has been added -- you can either create a new report using {blankReport: true} which will create a new report that is blank, and an empty dataset.   Or you can call the `newBlankReport()` function off the report generator to create a new blank report programatically.   

In addition on the main report you can now click the "Data" button, and see/edit the data for the report; and you can toggle if the data is saved with the report.    If you run the report w/ no data set; it will use the reports data; if you run the report with new data the new data will be used and override the reports embedded data.
