### ISSUE TITLE
[FRG] - Ability to add multiple sub-reports

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#126]
Right now it seems like you can only have one sub-report to a report, since there's only a subReport property which accepts one object.

**Comment by NathanaelA** [comment]
Can you give me an instance where you need another sub-report?    Sub-reports are created based on the data you send in.   So if you send in:
```
Master
  -> Detail
```
It creates a "Detail" subreport.    I haven't tested it but if you sent in:
```
Master 
   -> Detail 1
   -> Detail 2
```
I believe you should get two sub-reports.

**Comment by gillsonkell** [comment]
Say my data looks something like this:
```
{
    type_a_tests: [
        {
            type_a_name: 'A Test'
        }
    ],
    type_b_tests: [
        {
            type_b_name: 'B Test'
        }
    ]
}
```
I know I can make a sub-report for one of these with a report structure like this:
```
{
    name: 'test.pdf',
    subReport: {
        type: 'report',
        dataType: 'parent',
        data: 'type_a_tests',
        detail: [
            {
                type: 'print',
                field: 'type_a_name'
            }
        ]
    }
}
```
but how can I make two sub-reports, one for each?

**Comment by NathanaelA** [comment]
Yeah, I see your problem.    I'll look into updating the engine to support an array of subreports.

**Comment by NathanaelA** [comment]
Fixed in the latest release.
