### ISSUE TITLE
[FRG] - Allow data formatting

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#127]
I'm mostly looking for ideas on this problem. It feels like data formatting would be a reasonable thing for a reporting engine to manage, but I want to make sure it's done in an extendable way, so that multiple formats can be used or configured for a specific type.

When editing bands:
![Screen Shot 2019-12-26 at 3 42 05 PM](https://user-images.githubusercontent.com/193887/71491561-f8554f80-27f6-11ea-94cf-0e0d3c71e7a0.png)

I think it would make sense to see a "Format" option when you're editing a print or a cell. The value would get run through whatever format function is specified before printing. This would need to apply to totals as well. The Fluent engine has `.totalFormatter()`, but I think this type of functionality goes beyond that.

For the extendibility part, I'm curious what your thoughts are. I think that formatters would need to be able to be defined for when the report is generated. For example, in our system, we allow the user to choose between 24 hour time, and 12 hour time. So when our `displayTime()` method is called, it decides how it's supposed to format based on the user's preferences.

A simple, probably dumb way to do it, would be to manually define a list of functions in the configuration of the editor, then those could be chosen from in a dropdown added to the screenshot above. Then those functions would be called and used when the report is generated. If possible, those functions would need to support Promises (async/await).

That's just one idea though, like I said, I'm very open to better ones.

**Comment by NathanaelA** [comment]
Maybe make it simple stupid --- we can create a way for you to pass in an object like this:

`{"formatDate": displayTime, "SomeOtherFormatter": blahFormatter}`

Function would look like this;
```
function displayTime(inValue, callback) {
   const newValue = "Time: " + inValue; 
   callback(newValue); 
}
```

Where each function takes a value, and a callback (to allow it to be easily sync or async).
So then basically the report editor can show a select with `formatDate` and `SomeOtherFormatter`, then the values are sent to the formatter; and the formatter then calls the callback with the formatted value.   In side the function you can use promises/await/callback, or whatever method you want to do async functions....

Maybe this could be passed in as part of the Data or ReportData.

**Comment by beauwest** [comment]
I think that's similar, some pseudo-code just so I understand.

Client/Editor
```
const frg = new FluentReportsGenerator({
  id: 'fluentReportsEditor',
  data: [],
  report: {},
  formatterNames: ['formatDate', 'SomeOtherFormatter']
});
```

Server/Renderer
```
const reportBuilder = require('fluentreports/lib/fluentReportsBuilder').ReportBuilder;
const report = new reportBuilder({}, []);
report.formatters = {
  'formatDate': (inValue, callback) => {
    callback(`Time: ${inValue}`);
  },
  'SomeOtherFormatter': (inValue, callback) => {
    callback(`Other: ${inValue}`);
  }
};
report.render();
```

I think that's essentially what you're saying, right?

-----

Something else that came to my mind, that feels pretty dumb, but might work as well, is a simple data contract.

```
[
{amount: 123, amount-formatted: "$ 123.00"},
{amount: 4567, amount-formatted: "$ 4,567.00"}
]
```

Basically when any value is about to be printed, it checks for a `-formatted` version of the field, and uses that if it exists. There's some downsides to that. Efficiency, it puts the work on the developer to format all of their data, etc.

But one upside, is that I've been experimenting with using `worker_threads` to render reports. Getting 2+ seconds of blocking IO off the main thread sure is nice. To do it the first way, we'd have to go the route of a report worker pool, which is probably where we'll end up anyway.

------

I'm not stuck on either one of these, just throwing out ideas at this point.

**Comment by NathanaelA** [comment]
As for your first part; basically yes -- however I think we would need to pass in the formatter function (even if it is a dummy function) to the generator as you can preview reports.  So it has to be able to run it.
---
As for passing in `-formatted` if you are wanting to do this; then all you have to do is pass it into the report generator and set the label/band to print that field; and the engine actually doesn't have to do anything...  :)     

But it would be fairly easy for the generator engine to check for an `-formatted` value and pass it in instead.   The engine already does something similar to this for dealing with all printed items.

**Comment by beauwest** [comment]
> however I think we would need to pass in the formatter function (even if it is a dummy function) to the generator as you can preview reports. So it has to be able to run it.

At least in our case, I've overridden the preview functionality to be identical to running the report, so that would work the same either way.

My personal opinion is that's the direction we need to go. I like the simplicity from the report editor's perspective. As a user, I just:
- Add a print/band
- Choose a formatter function to use

And that's it. It complicates the server implementation slightly, but I think I'm happy to absorb the complication for the end user.

I want to do what's best for FluentReports as well though, so you may have an opinion on it as well.

**Comment by beauwest** [comment]
What are some usage guidelines for this?
- Can formatter functions be stored as JSON like other functions can be?
- What's the correct way to add formatter functions when rendering a report?

**Comment by beauwest** [comment]
After some debugging. I have left a few comments on the commits. This feature is non-functional right now, from what I can tell.

https://github.com/NathanaelA/fluentreports/pull/148/files
