### ISSUE TITLE
[FRG] - Sum total not working

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#128]
I would expect this report to show me 15, but instead it's blank:
```
{
  "name": "app.pdf",
  "groupBy": [
    {
      "groupOn": "group",
      "footer": [
        {
          "type": "band",
          "fields": [
            {
              "type": "text",
              "total": "amount"
            }
          ]
        }
      ]
    }
  ],
  "calcs": {
    "sum": [
      "amount"
    ]
  }
}
```
data:
```
[
  {
    "group": 1,
    "amount": 5
  },
  {
    "group": 1,
    "amount": 10
  }
]
```
Maybe I'm just missing something. Any help would be appreciated!

**Comment by gillsonkell** [comment]
OK, so I just figured out that if I move `calcs` into the group object, it works as expected. Now the only problem is that I don't seem to be able to do this from the GUI.

**Comment by NathanaelA** [comment]
You are correct, by default the renderer used to expect it at the group level.   However, the editor never expected groups to have separate totals...    

So two fixes:
1. Totals at the group level will be moved to the topmost level in the editor, this fixes a manual report being loaded in.   As technically this is how the engine expects it.
2. The JSON report renderer now will reparent the totals to the top most group which should solve all the totaling issues.   :D
