### ISSUE TITLE
[FRG] - Error when using group by

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#129]
When I group by "group" on this data and then try to open the sections screen, I get this error:
```
Uncaught TypeError: Cannot read property 'groupBy' of undefined
    at FluentReportsGenerator._generateSave (fluentReportsGenerator.js:560)
    at FluentReportsGenerator._openSections (fluentReportsGenerator.js:939)
    at HTMLAnchorElement.<anonymous> (fluentReportsGenerator.js:960)
```
Data:
```
[
  {
    "date": "01/01/2020",
    "items": [
      {
        "group": 1,
        "number": 1
      },
      {
        "group": 1,
        "number": 2
      }
    ]
  }
]
```

**Comment by NathanaelA** [comment]
Is their a specific report you are using; or you are attempting to create a new report?

**Comment by gillsonkell** [comment]
This is when I create a brand new report. I initialize the generator with an empty object for the report data, add a group by for "group" from the GUI, click sections, and get this error.

**Comment by NathanaelA** [comment]
I believe this should be fixed as of a month or so ago, can you confirm?

**Comment by gillsonkell** [comment]
Yes that seems to be working now, thanks!
