### ISSUE TITLE
[FRG] - Add ability to add newline characters to band text

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#131]
When I type "\n" into the band text it currently gets escaped.

**Comment by NathanaelA** [comment]
I assume you mean it will print a "\" and then a "n".  Correct, if so this is the correct behavior as end users are going to have no clue why a "\n" would turn into a linefeed and a "\t" would turn into a tab; they would just type "hi\test" and expect it to print "hi\test".    

Now if you believe you need the ability to add a cr/lf in the text; maybe we need to think a way to do that from the GUI...

**Comment by gillsonkell** [comment]
Yeah, that's fine! I just need the ability to make newlines somehow. Maybe if the text input was a textfield instead.

**Comment by beauwest** [comment]
It feels like this needs to go beyond just the GUI. For example, we have some reports where headers are dynamically generated. There are also plenty of instances where we're printing data that is multiline, for example a comment field.

I think that my personal preference would be that the strings are not escaped before they're printed. I haven't dug into the specifics for PDFKit, but I think that'd be my expectation.

```
const comment = 'line1\nline2';
```

If I do a "print" and pass in the Javascript variable `comment` I expect it to print two lines.

**Comment by gillsonkell** [comment]
@beauwest I think that is the current behavior, the only time strings are escaped that I know of are when inputted directly from the GUI. If you print a data field those newline characters aren't stripped. Or are you saying if you type a "\n" into the band text field from the GUI you don't think it should be escaped?

**Comment by beauwest** [comment]
Oh no, I probably think that the GUI should support multi-line. I'm talking about data coming in from Javascript.

**Comment by gillsonkell** [comment]
Strings that come from JavaScript aren't currently escaped, just strings inputted from the GUI. So whether you print a function value with:
```
return 'line1\nline2';
```
or modify the report structure before printing like:
```
report.detail[0].text = 'line1\nline2';
```
The newlines will appear.

**Comment by NathanaelA** [comment]
I'll look into having a way to do a text field on text input...  That does seem to make the most sense from the GUI side and easiest for a end user to use.
