### ISSUE TITLE
[FRG] - Font size getting reset

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#132]
I have a label in my title header with a certain font size, but whenever I create a new instance of ReportBuilder it leaves out the font size in the GUI, and when I save it again the font size adjustment is taken out.

**Comment by NathanaelA** [comment]
Sorry, not understanding the issue.    Are you setting the font size in the header and it is keeping it on the next report; or the font size is not saved at all on the header?

**Comment by gillsonkell** [comment]
Sorry, I mean when I try to load the editor with this in my report data:
```
{
	"type": "print",
	"text": "Hello, world!",
	"settings": {
		"fontSize": 16
	}
}
```
the font size doesn't load. So if I go click on the label, the font size field is blank.
