### ISSUE TITLE
[FRG] - Add "New Page" button

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#139]
Add ability to do what report.newPage() does from the GUI. Basically when it gets to this point it breaks off to another page.

**Comment by NathanaelA** [comment]
New element PageBreak element that is functionable active has been added; in addition each section can now have a page break settings of "before", "after" or "auto".    As most reports you will probably just use the pageBreak settings on a section to force a break before/after that section has printed.
