### ISSUE TITLE
Report generation issue – stream.push() after EOF

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#147]
There was an issue reported to me by one of our developers. They were able to provide a reproducible test report. I've attached it here: [test.js.zip](https://github.com/NathanaelA/fluentreports/files/4078372/test.js.zip)

In our production environment, we see a "stream.push after EOF" error, here are the notes from the developer
> I do not receive an error when running this report manually, but my system cannot open the generated PDF. Changing the “-75” near the bottom to a “-200” results in a PDF that my system can open normally.

**Comment by NathanaelA** [comment]
I cannot duplicate the issue with the latest version; but I suspect the issue was also fixed in #152 as it appears to hits the same edge case that #152 hit.  Which corrupted the output buffer.
