### ISSUE TITLE
Corrupted PDF when banding to report.maxY() - report.heightOfString() - 2 with a gutter

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#152]
When banding a gutter with a gutter amount to a particular position at the bottom of the page the report becomes corrupted:
```
const Report = require('./fluentreports/lib/fluentReports.js').Report;

new Report()
  .detail((report, data) => {
    report.currentY(report.maxY() - report.heightOfString() - 2);
    report.band([
      {
        data: 'Detail'
      }
    ], {
      gutter: 1
    });
  })
  .data({})
  .render((error) => {
    if (error) {
      throw error;
    }
  });
```
If you have a header and something printing after the band, the header goes missing on the next page, instead:
```
const Report = require('./fluentreports/lib/fluentReports.js').Report;

new Report()
  .groupBy()
  .header((report) => {
    report.print('Header');
  })
  .detail((report, data) => {
    report.currentY(report.maxY() - report.heightOfString() - 2);
    report.band([
      {
        data: 'Detail'
      }
    ], {
      gutter: 1
    });
    report.print('This will keep the PDF from coming out corrupted, but the header will not appear.');
  })
  .data({})
  .render((error) => {
    if (error) {
      throw error;
    }
  });
```
A workaround to this issue appears to be to set the `collapse` to `true`.

**Comment by NathanaelA** [comment]
You found an interesting corner case when it would exceed the page size and trigger a new page; but the new page didn't have any data (which would trigger a deletion of that page when writting out); however, the pdfkit must have change some code in a later version and this edge case broke again.

It is fixed in the next version.
