### ISSUE TITLE
[FRG] - Make positioning more intuitive

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#157]
I wanted to create a simple two-column layout.

**Expectation**
I add two "Print label" elements. Position one on the left-side. Position the second one near the middle.

<img width="1033" alt="Screen Shot 2020-02-22 at 12 45 53 PM" src="https://user-images.githubusercontent.com/193887/75097525-483f6100-5571-11ea-8142-c85d7dda911c.png">

It created both with a "Add Y" value of 40.

**Result**
The Add Y ends up causing the actual Y value to grow, and not be the same for both. It ends up being Element1Y + Element1Height + Element2AddY.

<img width="1033" alt="Screen Shot 2020-02-22 at 12 48 36 PM" src="https://user-images.githubusercontent.com/193887/75097558-aff5ac00-5571-11ea-98d0-4d28c6c0f0ab.png">

Ideally the visual editor would more accurately represent the end result, but I understand the challenges of that, especially with the dynamic nature of reports. I would imagine a system where the AddY is actually a relative Y value from the top of the report section, not just based on the previous element. You'd probably need both an AddY and a SectionOffsetY or something like that though, because the AddY property is useful in other instances.

**Comment by beauwest** [comment]
I have been thinking about this more. In a [comment on another issue](https://github.com/NathanaelA/fluentreports/issues/160#issuecomment-593421654), I provided a sample report. Attached is the way that report looks in the editor.

![Screen Shot 2020-03-02 at 8 16 18 AM](https://user-images.githubusercontent.com/193887/75684291-1eb3c300-5c5e-11ea-965b-de2891c56c24.png)

Because of the nature of the editor and the positioning, everything ends up stacked on top of each other, which makes creating and editing the reports difficult.

Do you have any ideas on how to make editing the reports easier? Or are we using the tool incorrectly?

**Comment by beauwest** [comment]
If you get to a point where you're working on this, I'm starting to get a decent collection of reports written in the new FRG style. If you end up wanting additional examples, feel free to shoot me an email and I can get you some sample data and JSON structure objects.

**Comment by beauwest** [comment]
I've just gotten to the point where I was able to test the new positioning system, using `absoluteX`/`absoluteY`.

Wow! It's so much easier to use. Thank you!

**Comment by NathanaelA** [comment]
Yeah, it makes it night and day difference.
