### ISSUE TITLE
[FRG] - Unable to use "Print dynamic data" to print variables

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#158]
Whenever I try to use the Print dynamic data option to print a variable, I end up with an error when I try to click the Save action.
> Cannot read property '_parseElement' of undefined

Inside of the `_parseSection()`, "print" block, it falls all the way through to
```
printElement._parseElement(data);
```

I'm assuming it's not being caught on a `} else if (data.variable) {`, on line 1616.

`data` is
> type: "print"
settings: {align: 0}
variable: undefined

**Comment by NathanaelA** [comment]
This is fixed in the current version.
