### ISSUE TITLE
How to repeat table header on each page?

### ISSUE THREAD

**Issue by risoldi** [Nathanaela/fluentreports#16]
Hello,

by looking at the examples and at fluentReports' code, it is not clear to me whether it is possible to repeat a table header at the beginning of each page, in the case where a table spans multiple pages. Is there such an option?
My idea is to have the header repeat at each page, and also to insert a partial total which is reported at the beginning of each page (say I have a sum on an "amount" field, at the beginning of each page I'd like to know how much that sum is worth at that point).

Thanks,
M.

**Comment by Nathanaela** [comment]
Please note this is now fixed in v1.00   :grinning:
