### ISSUE TITLE
[FRG] - Cannot load reports with image elements

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#160]
When I create a report, and add an image, I end up with an error when I try to load the report, or when the save is called.

> Element: ParseElement should be overridden
> {type: "image", image: "data:image/png;base64,iVB… etc

The image data appears to be in the report structure, but no preview (like when it's first added) and it will not print on the report.

**Comment by NathanaelA** [comment]
In the newest verson of the report generator and builder I am unable to duplicate the issue;
I tested it with a simple report and after dropping an image in the report I did:
1. Print (which saves the report before printing it)
2. Copied the saved report into a brand new test report to run from node directly (i.e. not in the browser).

Both methods took the image perfectly fine:
![image](https://user-images.githubusercontent.com/850871/75650938-f9529500-5c1c-11ea-8fa2-75fafecd9993.png)

**Comment by beauwest** [comment]
It still fails for me. I modified the demo HTML page in the repository. See attached.

[reportgenerator.txt](https://github.com/NathanaelA/fluentreports/files/4275806/reportgenerator.txt) (renamed to .txt for Github)

All I do, is open that .html document in Chrome. And I still receive:
> Element: ParseElement should be overridden

**Comment by NathanaelA** [comment]
@beauwest - Thank you for the example -- I was able to see what the issue was and fix it.   :grinning:
