### ISSUE TITLE
color-filling cells overflows on page breaks in a single group

### ISSUE THREAD

**Issue by radovanvacek** [NathanaelA/fluentreports#173]
Hi,

If a group spans over multiple pages and a cell in the the last row is is color-filled, the fill overflows until the end of the paper. This happens because of line 2901 of fluentReports.js, where you call
`this._PDF.rect(x + offset, y, x + offset + curWidth, y + height)`

However, the _PDF.rect takes X, Y, width, height not X1, Y1, X2, Y2, see pdfkit/mixins/vectors.js, line 97: `rect: function(x, y, w, h) ` .

The fix is easy, just replace line 2901 with `this._PDF.rect(x +offset , y, curWidth, height);` . There is also an issue with the padding, but i didn't have time to debug that properly yet.

Hope this helps.

Best
Radovan

**Comment by NathanaelA** [comment]
Thanks for the report; their is actually a PR #169 that fixes it -- I will be reviewing all the PR's later today...
