### ISSUE TITLE
[FRG] Support drawing a horizontal line shape

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#176]
I'm assuming the correct method to draw a horizontal line, is to set the "Height" to 0. However, when I do that, it seems to default it to a "50" value internally, which ends up drawing a diagonal line.

**Comment by NathanaelA** [comment]
Fixed in v1.3.2

**Comment by beauwest** [comment]
Hey @NathanaelA, we're trying to do horizontal lines again, and it's not working. Same behavior as the original problem. I cannot create a horizontal line through the editor.
