### ISSUE TITLE
Encountering page footer issue if margins are set on four sides

### ISSUE THREAD

**Issue by jhen913** [Nathanaela/fluentreports#18]
Hi Nathan,

There is a page footer issue if I set the margins on four sides of the page like this:

var report = new Report("test.pdf", {paper: "letter"});
...
report.margins({left: 50, bottom: 5, right: 0, top: 0});
...

The footer size is not being considered when rendering resulting to page footer being printed on the next page.

However, when I set the margins like this:

var report = new Report("test.pdf", {paper: "letter"});
...
report.margins(50);
...

I am not encountering any issue. I hope you can look into this. Thank you!

**Comment by Nathanaela** [comment]
Please note this issue is now fixed in v1.00
