### ISSUE TITLE
[FRG] Fixed Height section resizes based on contents

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#195]
I'm trying to create a fixed-height header for a group. I created the header, put a whole bunch of prints into it, set it to fixed height of 200. But because of the 9 elements inside of it, it automatically resizes to 312. 

The 9 fields are in 3 different columns, but it feels like the UI is forcing it to a certain height anyway. It'd be nice if there wasn't a minimum height based on what's inside of the section.

**Comment by NathanaelA** [comment]
I am a bit confused by this; the only reason it should resize the height of the section is if you have something outside the section, so that you can get access to edit/move that object.   If you are seeing something different, can you send me a sample json report that duplicates the issue?

**Comment by beauwest** [comment]
Sure, here's a simple structure with a titleHeader

```
{"name":"report.pdf","type":"report","fonts":[],"version":1,"fontSize":0,"autoPrint":false,"paperSize":"letter","variables":{},"titleHeader":{"height":60,"children":[{"text":"Label 1","type":"print","settings":{"absoluteX":0,"absoluteY":0}},{"text":"Label 2","type":"print","settings":{"absoluteX":0,"absoluteY":20}},{"text":"Label 3","type":"print","settings":{"absoluteX":60,"absoluteY":1}},{"text":"Label 4","type":"print","settings":{"absoluteX":60,"absoluteY":20}},{"text":"Label 5","type":"print","settings":{"absoluteX":120,"absoluteY":1}},{"text":"Label 5","type":"print","settings":{"absoluteX":120,"absoluteY":20}}],"fixedHeight":true},"paperOrientation":"portrait"}
```

The key parts are
- No child exceeds an absoluteY of 20
- The titleHeader is set to fixedHeight, with a height of 60.

If you load that structure into FRG, the titleHeader will "reset" the height to 216. Resulting in the next save changing the `height` property to 216.

One of the uniqueness of our implementation of FRG, is that we save & reload reports into the editor _a lot_. I use
```
this.fluentReports.setConfig('report', newValue);
```

We're giving that reload piece a thorough testing. 🙂
