### ISSUE TITLE
Possible bug when piping to write stream

### ISSUE THREAD

**Issue by leoncc** [Nathanaela/fluentreports#20]
Hi,

I think : this._parent = null is needed as per below maybe (in fluentReports.js)?. Else you get an error later: cannot call render on undefined.     

function Report(parent, options) {
        .......
            } else if (typeof parent === "object" && typeof parent.write === "function" && typeof parent.end === "function") {
                  this._parent = null;
                  this._outputType = Report.renderType.pipe;
                  this._pipe = parent;
            } else {

**Comment by Nathanaela** [comment]
Good catch...  You are correct that is missing...   I've updated master; and will push it soon.
