### ISSUE TITLE
[FRG] Change the order of alignment options

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#212]
So, this is a minor thing, but it always is a gotcha for us if we're moving quickly.

The Alignment dropdown options are listed as
```
Left
Right
Center
```

But our brains always think it should be
```
Left
Center
Right
```

Not a huge issue, but might be a nice QoL thing.

**Comment by NathanaelA** [comment]
We will get this in the next version...  :grinning:

**Comment by NathanaelA** [comment]
Fixed in v1.3.5 - In addition, a "None" has been added to the list as the default; If you put "Left", "Center" or "Right" it will override the X coordinate, so "None" allows the X coord to position items in a specific x coordinate.
