### ISSUE TITLE
[FRG] Band Line element always floats to the top of the section

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#213]
If you load a report structure that has a band, and then a band-line in the section, the band line will always float to the top of the section. (doesn't have an absolute Y?)

It overlaps other things right now
![Screen Shot 2020-08-27 at 4 06 08 PM](https://user-images.githubusercontent.com/193887/91494907-42f40380-e87f-11ea-87ba-5130849f2650.png)

**Comment by beauwest** [comment]
Same problem with pageBreak elements.

**Comment by NathanaelA** [comment]
Fixed in v1.3.5
