### ISSUE TITLE
[FRG] Provide a way to duplicate elements

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#214]
We've found it would be useful to be able to duplicate elements. For example, if we create a band for our data, and we want to create a footer that has the same widths, cells, formatters, etc. We'd love to be able to duplicate it, and just change the values for the cells.

**Comment by NathanaelA** [comment]
Added CTRL-C/CTRL-X/CTRL-V and duplicate button in v1.3.5.
