### ISSUE TITLE
[FRG] Delete key on OSX deletes label while editing text

### ISSUE THREAD

**Issue by ahenager** [NathanaelA/fluentreports#225]
The delete key on Mac style keyboards is the backspace key unless used in conjunction with the fn key. With version 1.3.5/1.3.6, when editing the text of a label, if this key is pressed, it deletes the whole label. This makes it impossible to backspace over text in a label from a Mac.

**Comment by NathanaelA** [comment]
Interesting, the delete is not supposed to work while in a contenteditable while editing the content. 
1. Is this in the property editor or directly editing the content in label (i.e. contenteditable)?
2. Is this Safari or any browser?

**Comment by ahenager** [comment]
1. This occurs both in the property editor and in the contenteditable label.
2. This is in Chrome. I tested this also in Safari and it is the same, except that I don't seem to be able to make the contenteditable kick in, but it still happens in the property editor.

**Comment by beauwest** [comment]
Oops, I didn't see this one and accidentally created a duplicate. #227.

The duplicate has some more information about the cause of this though.

**Comment by NathanaelA** [comment]
Thank you @beauwest - That explains why I can't duplicate the issue and what the source of the issue is.   We will see if your code will solve the issue; but I will need you guys to verify it fixes it for you.  :grinning:

**Comment by beauwest** [comment]
I was doing some research, and an untested alternative to what I posted in the other thread would be something like
```
this._elementDiv.getRootNode().activeElement
```

[`getRootNode()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) looks like it was designed to handle this type of scenario. It will return the root of whatever element you specify.

**Comment by NathanaelA** [comment]
Well your code in #227 actually worked with a minor change to allow me to detect for the contentEditable also(as you can double click in a couple of the label types and directly edit in them).    I ran several tests in my test html that makes FR a web component and my normal test bed and everything seems to work correctly with the changes in the new v1.3.7 I just pushed.

**Comment by beauwest** [comment]
Pulled it in and tested this morning and it works great. Thank you!
