### ISSUE TITLE
Force New Page

### ISSUE THREAD

**Issue by johntom** [Nathanaela/fluentreports#23]
Hi,
What a awesome repo this is, imho designing reports are much better/faster than pdfkit. Is there a way to issue a page break?
TIA
John

**Comment by Nathanaela** [comment]
While in your data, header or footer statement; the newPage() function will create a new page.

var data = function(Rpt, data, state) {
  if (data.someValue === 1) {
     Rpt.newPage();
  } 
  Rpt.print(["something cool", data.someOtherValue])
}

See: [Docs](https://github.com/Nathanaela/fluentreports/blob/master/commands.md#newpage--saveoptions-callback-)

**Comment by johntom** [comment]
Thanks, I was looking for the documentation and just didn't see the command.md file.
