### ISSUE TITLE
[FRG] Prevent page break before multi-page section

### ISSUE THREAD

**Issue by ahenager** [NathanaelA/fluentreports#232]
Whenever a section is more than one page long -- using the page break element -- there is always a page break inserted following the previous section. In my case, I have a group footer, followed by a final summary that is multiple pages long. I want the final summary to begin on the same page as the group footer, but I cannot currently find a way to accomplish this.

**Comment by NathanaelA** [comment]
Can you create me a sample report that duplicates this behavior; I'm not 100% sure how to duplicate your issue.

**Comment by ahenager** [comment]
So in the process of creating an example report for this, I moved the page break on the third page of my final summary slightly and it resolved my issue. I'm thinking this must have been due to some legacy style JSON in my report. Sorry for the false alarm!
