### ISSUE TITLE
[FRG] Line elements shift position when structure is loaded

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#236]
When I add a horizontal line element to a report, then save & reload that report, the line element shifts to the wrong location.

Here is a simple report structure
```
{"name":"report.pdf","type":"report","fonts":[],"footer":{"children":[]},"header":{"children":[]},"version":2,"fontSize":0,"autoPrint":false,"paperSize":"letter","variables":{},"pageHeader":{"children":[{"type":"shape","settings":{"top":200,"shape":"line","width":468,"height":0,"radius":50}}]},"paperOrientation":"portrait"}
```

If I save and reload the report structure multiple times, it every time it shifts the line element up.

Starting at the assigned starting "top", with each save & reload, the top ends up getting lower.
1. 200
1. 133
1. 59
1. 39
1. 26
1. 17
1. 11
1. 7
1. 5

**Comment by NathanaelA** [comment]
Fixed in next version.
