### ISSUE TITLE
ReportRenderer.newline(X) breaks rendering report.

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#24]
When trying to do `ReportRenderer.newline(2)` inside of a `.detail()` function. The entire report no longer works.

![screen shot 2015-08-06 at 10 53 55 am](https://cloud.githubusercontent.com/assets/193887/9116327/753e9ace-3c29-11e5-99d5-ee4c6886ae14.png)

**Comment by Nathanaela** [comment]
Beau, I am unable to duplicate this.   I tried it both in a normal Synchronous report; which then is
**report.newLine(2);**   in side the detail function.   And I tried it in an Async mode report; which then means you have to do:  **report.newLine(2, callback).**   If this is in that Kellpro internal project, you would do **report.newLine(2, _);** if the report is in Async mode.

**Comment by NathanaelA** [comment]
I assume since that the above answered the question.   Re-open their still is a issue.
