### ISSUE TITLE
[FRG] Remove requirement of “report group” column in data

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#245]
When trying to add a header/detail/footer, it appears that unless you provide a groupBy, it will break every record into its own group.

A workaround is to add a `"report_group":1` to every row in the data, but it’d be really nice to be able to create reports without requiring a group.

**Comment by NathanaelA** [comment]
Can you share a sample report, my guess is you are adding a header/footer into the grouping system not the title header/footer, and as such it needs something to "group" by.

**Comment by NathanaelA** [comment]
Unless we are missing something, I just tested this, adding a " Page Header " and a " Page Footer ".  Increased your data items to have enough to generate several pages and it printed this:
![image](https://user-images.githubusercontent.com/850871/140439134-925979bf-883f-4c9a-829c-c0f9aaa3296b.png)

Never added any group to the repor.
