### ISSUE TITLE
Setting the report font does not work

### ISSUE THREAD

**Issue by beaudesigns** [Nathanaela/fluentreports#25]
Tried setting it with `.font` off the report object, as well as in a band

```
x.band([{data: 'Sample Data'}], {x: 10, font: 'times'});
```

Neither method changed the font.

**Comment by Nathanaela** [comment]
The exact font should be "Times-Roman" if you want times.  
The built in fonts are:
"Courier", "Helvetica", "Times-Roman", "Symbol", and "ZapfDingbats" -- if you want to add any other fonts you need to use the addFont command then you can use them.

**Comment by beaudesigns** [comment]
Submitted a pull request:

https://github.com/Nathanaela/fluentreports/pull/27
