### ISSUE TITLE
Use fluentreports with VUE

### ISSUE THREAD

**Issue by froschi123** [NathanaelA/fluentreports#265]
Hi, i like the approach of your fluentreports and would love to integrate it into a vue application.

Is this possible at all? So far i could not figure out, how to do this. 
If i install fluentreports with npm and try to use your simple sample in a vue page, i get a bunch of errors, telling me, that there are several references missing.

Do you have an example of vue integraiton? I could not find any at all.

Thanks
Bernd

**Comment by NathanaelA** [comment]
It should work fin in Vue, however I haven't generated any demos of it.   All you really need to do is follow:
- https://github.com/NathanaelA/fluentreports/tree/master/generator
To generate the browser version, assuming you want to have it all generated and ran from the browser.
