### ISSUE TITLE
_renderFooter error when adding multiple sub reports

### ISSUE THREAD

**Issue by AlanFonderflick** [NathanaelA/fluentreports#28]
Hi,

Thanks for your work on this project. I raised some issue when tried to add multiples sub reports on a main report, like this :

     var mainReport = new Report('assets/report.pdf')
            .data(formData)
            .pageheader('test')
            .footer('test')
            .pageFooter('test');

            var overviewReport = new Report(mainReport)
            .data(formData)
            .titleHeader('title1');

            var introductionReport = new Report(mainReport)
            .data(formData);

My goal is to use these subreports as "modules", and rendering later only selected subreports in the main report.
When rendering, i get an error on _renderFooter property of children, on line 3927 of fluentReport.js :

        _renderFooter: function (Rpt, State, callback) {
            var i, cnt = this._children.length, done = -1;
            var self = this;

            var renderFooterHandler = function () {
                done++;
                if (done === cnt) {
                    callback();
                } else {
                    self._children[done]._renderFooter(Rpt, State, renderFooterHandler);
                }
            };

            if (callback) {
                renderFooterHandler();
            } else {
                for (i=0;i<cnt;i++) {
                    this._children[i]._renderFooter(Rpt, State); //_renderFooter is undefined :(
                }
            }
        },

I tried to use these reports with and without footers, but I can't figure out what I'm doing wrong ; your code seems to basically manage multiple children reports.
Can you give me a sample code of multiple subreports ?

**Comment by NathanaelA** [comment]
I'll take a look at it. Their was some serious rewriting for version 1.0 and so it is possible something was missed on sub-reports...

**Comment by NathanaelA** [comment]
@AlanFonderflick -- Sorry about the lengthily delay in looking at this -- I have been totally swamped.  But it is now fixed in the latest version!
