### ISSUE TITLE
Render data that contains boolean value

### ISSUE THREAD

**Issue by sentient** [NathanaelA/fluentreports#30]
Let data be

var data = [ { hasProp1: true, hasProp2: false, hasProp3: true }];

 var rpt = new fluentreports.Report('buffer');

 rpt.data(data)
      .margins(20)
      .detail("{{hasProp1}} - {{hasProp2}} - {{hasProp3}}");

Will genererate

true - {{hasProp2}} - true

---
In order to test if a data value exists you might have to use
if (typeof obj.prop !== 'undefined) ...

and not
if (obj.prop) ...

**Comment by NathanaelA** [comment]
Thanks good catch!

**Comment by NathanaelA** [comment]
This is fixed in the latest release.  Thanks again.
