### ISSUE TITLE
use userData

### ISSUE THREAD

**Issue by sentient** [NathanaelA/fluentreports#31]
in the documentation (and also examples) you mention how to set userData
by
rpt.userdata({hi:4})

I noticed it is all lowercase 'userdata' and not camelCase 'userData' 

I could not find an example where you were actually using this data in a report or a detail report.

I tried 

report.userData.hi

report.userData().hi

...

I do have a use data where I would like to store some data in an object that is accessed later in generating links in the 
.details(function(report,data){
  var myUserData = report.userData; ??
})  

I must be missing something...

**Comment by NathanaelA** [comment]
Hmm, let me look I could have sworn I had an example.   But it is also possible that I broke this with the 1.0 release.  I'll take a look and see if I can get back to you shortly.

**Comment by NathanaelA** [comment]
I'll test it but looking at the code you should have been:
```js.
details(report, data) {
  var myUserData = report.userData();
  // do something with it...
}
```

**Comment by NathanaelA** [comment]
You are correct; I was able to spend a bit of time mocking up a report a couple days ago.  I have fixed the issue in the latest version.   Thanks for letting me know.
