### ISSUE TITLE
Error: Report is not a function

### ISSUE THREAD

**Issue by shrirammano** [NathanaelA/fluentreports#33]
Hi,

I am trying to use fluentreports in my node js project, where I have the following code(which I copied from the readme section) in a file which is used by route.

```
var Report = require('fluentreports');
module.exports.generateReport = function(next){
	var data = [{name: 'Elijah', age: 18}, {name: 'Abraham', age: 22}, {name: 'Gavin', age: 28}];
	var rpt = new Report("Report.pdf")        
			.pageHeader( ["Employee Ages"] )      // Add a simple (optional) page Header...        
			.data( data )                         // Add some Data (This is required)
			.detail( [['name', 200],['age', 50]]) // Layout the report in a Grid of 200px & 50px
			.render();
}
```

But when I call the above method, I am getting an error which says
**{"message":"Report is not a function","error":{}}**

Is this an issue? Or if am using it wrong?

Thanks.

**Comment by NathanaelA** [comment]
If I had a guess, I would guess that you hadn't did a **npm install fluentreports**    The only other possibility would be if somewhere between the var Report = require('fluentreports') you had something else that did var Report=somevalue; so that you redefined Report.

**Comment by NathanaelA** [comment]
Are you still having this issue?

**Comment by jgdovin** [comment]
If you look at the examples you should change that to
`var Report = require('fluentreports').Report`

**Comment by lyndontavares** [comment]
Hi, Good job!
you can add some example for angular?

**Comment by NathanaelA** [comment]
@lyndontavares I haven't really used Angular, however I am looking at Angular 2...   Would that work?
