### ISSUE TITLE
Times-Roman not working with fontBold attribute

### ISSUE THREAD

**Issue by christensson** [NathanaelA/fluentreports#34]
If font is set to "Times-Roman" and fontBold attribute is set true in for example a .band() construct the font face doesn't change. However if font is set to "Helvetica" everything works as expected.

Howto reproduce:
1. Go to the demo-page: http://www.fluentreports.com/demo.html
2. Add fontBold: true to for example line 43 to render the "Date:" string in bold face using "Times-Roman". Nothing happens.
3. Modify the font on line 47 to "Helvetica" and now the "Date:" string is rendered using bold font face.

**Comment by christensson** [comment]
Found out that the problem is that in the fontBold function, the font is selected using the following expression:
`var font = this._fonts[this._PDF._font.filename || (this._PDF._font.font.attributes &&  this._PDF._font.font.attributes.FamilyName) || this._PDF._font.name];`
However, this._PDF._font.font.attributes &&  this._PDF._font.font.attributes.FamilyName evaluates to "Times" which this._fonts doesn't contain. A work-around is to evaluate this._PDF._font.name before the family-name expression.
Possible fix:
`var font = this._fonts[this._PDF._font.filename || this._PDF._font.name || (this._PDF._font.font.attributes &&  this._PDF._font.font.attributes.FamilyName)];`

**Comment by christensson** [comment]
See possible fix in https://github.com/NathanaelA/fluentreports/pull/36

**Comment by NathanaelA** [comment]
Ah, yes -- thanks for the report and tracing it down.

**Comment by NathanaelA** [comment]
I have pushed v1.06; and I added the same patch for Italic and normal, so that it should work properly in all cases again.   Thanks again.
