### ISSUE TITLE
`pageNumber` does not display on the final page.

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#38]
I'm using `pageFooter`.

```
report.pageFooter(footerGenerator);

var footerGenerator = function (reportObject) {
  reportObject.fontSize(7);
  reportObject.pageNumber({footer: true, align: 'right', text: 'Page {0}'});
  reportObject.fontNormal();
};
```
 The page number shows on every page except the final page.

**Comment by NathanaelA** [comment]
Any chance you have a Summary Footer on this report?   A summary footer takes presidence over a normal footer just like a Title Header will replace a header on the first page.

**Comment by beaudesigns** [comment]
Yes, sorry, I missed that in the documentation.
