### ISSUE TITLE
I would like `pageNumber` to have access to the total number of pages

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#39]
Currently, the `text` for the `pageNumber` function is: "Page {0}". I would like to be able to do: "Page {0}/{1}", with {1} being the total number of pages.

**Comment by NathanaelA** [comment]
Duplicate of #12

**Comment by NathanaelA** [comment]
@beaudesigns If Kellpro is interested in sponsoring this feature; let me know, otherwise this features as you can see from #12 it is a fairly low priority feature (I put it in Jul 2014); that has currently no time table for me to actually worked on it as nothing I am doing requires a .page count.

**Comment by ahenager** [comment]
We are interested in sponsoring this request. Shoot me an e-mail with an estimate.
