### ISSUE TITLE
Concept of label or container box

### ISSUE THREAD

**Issue by davistan** [NathanaelA/fluentreports#41]
Hi and cool project here. This is an ambitious project and would love to see this moving.

FYI, we have developed some business programs and uses 3rd party commercial reporting modules.

For the reports, I don't see any way to define labels or boxes and then bind data into them. This will be helpful for (when creating report designer) reports to adjust text-wrapping / auto-grow, etc.

**Comment by NathanaelA** [comment]
The primitives are already their to do all of that.  Print & bands allow you to do pretty much everything to a pixel perfect degree.

fluentReports is in use in several places generating hundreds of different types of reports everything from simple labels, invoices & checks to complex multipage reports that have detailed documentation that the government needs for detailed accounting records.

  If someone wanted to sponsor or develop something like a report designer; it could easily be done with the fluentReports framework probably without any changes done to fR base code.
