### ISSUE TITLE
Page height

### ISSUE THREAD

**Issue by tasca05** [NathanaelA/fluentreports#45]
Hi, I'm getting this Feedback

REPORTAPI: Your Report's Page Footer exceeds the page bottom margin ( 821.89 ) by  10.110000000000014 -- Please subtract 10.110000000000014 pixels from (probably) where you set Y to 735.89

var rpt = new Report(rp)
      .margins({ left:30, top: 30, right: 30, bottom: 30 })
      .paper("A4")
      .autoPrint(false)
      .pageHeader(header)
      .data( nt.lotes )
      .detail( lotesDetail )
      .sum( "valorVenda" )
      .pageFooter(summary)
      .fontSize(9);

what am I doing wrong?

another question, with align = "justify"

thanks

**Comment by NathanaelA** [comment]
The warning is telling you that your footer is exceeding the size of the bottom margin. So if you look at the pdf; the footer is probably exceeding by 10px into you 30px bottom margin...  So most likely your summary() function has a place where it is going to a specific coordinate and then prints enough to enter the border area...

**Comment by tasca05** [comment]
Yes, is correct.

as I disable msg.

thanks
