### ISSUE TITLE
Rotated text

### ISSUE THREAD

**Issue by ahenager** [NathanaelA/fluentreports#46]
I'd like to request the ability to write text rotated a certain number of degrees. I'm not particular about how we do it, perhaps something like `print('Some Text', {rotate:90})`. It seems like it would be easiest if this would simply render the text onto the report and leave the Y and X the same as when we started. KellPro is interested in sponsoring this, so shoot me an e-mail with a quote if you'd like to implement this for us.

**Comment by NathanaelA** [comment]
This has been added in fluentReports 1.09 - Thanks to Kellpro for sponsoring this cool feature.  

The demo3.js file has been updated to show how to use the new rotate command and even how to have a cool "confidential" faded out in the background of the entire page.  :grinning:
