### ISSUE TITLE
finalSummary disappears

### ISSUE THREAD

**Issue by android-sos** [NathanaelA/fluentreports#49]
finalSummary disappears when all items of detail have been printed at end of a sheet as seem in these pdf.
[1.pdf](https://github.com/NathanaelA/fluentreports/files/427763/1.pdf)
[2.pdf](https://github.com/NathanaelA/fluentreports/files/427764/2.pdf)
Please some adviced in order solve this, it shoulnd.t be a issue.

**Comment by NathanaelA** [comment]
I would have to see the JavaScript code you used to generate the report to see what the issue is.  If you want you can generate a sample JS code that generates the issue and I will figure out why.

**Comment by android-sos** [comment]
I appreciate your help, Thx
With this code I make the repot: list_diario_legal_detallado.js

`
var Report = require('fluentreports').Report;

exports.printreport = function (options, ruta, callback) {
    'use strict';
    options = options || {};
    var Current_Date = new Date().toDateString();
    var headerFunction = function(rpt, data) {
        // Confidential text, we need this first because everything else prints on top of it
        rpt.print(options.marcaAgua, {x: 40, y: 610, rotate: 310, opacity: 0.5, textColor: '#EEEEEE', width: 1000, fontSize: 127});

        // Company Info - Top Left
        rpt.setCurrentY(14);
        rpt.setCurrentX(20);

        if (options.image) {
            rpt.image(options.image, {width: 60});
        }

        rpt.fontSize(10); 
        rpt.setCurrentY(20);
        rpt.pageNumber({text: "Página : {0} of {1}", footer: true, y: rpt.currentY() + 10 , align: "right"});
        var pxc = 95   
        if (options.company) rpt.print(options.company, {x: pxc});
        if (options.rif) rpt.print(options.rif, {x: pxc});
        if (options.address) rpt.print(options.address, {x: pxc});
        if (options.city && options.state && options.postal) {
            rpt.print(options.city + '-' + options.state + ', Postal: ' + options.postal, {x: pxc});
        }
        rpt.print(options.horaImpresion, {footer: true, y: rpt.currentY() - 22, align: "right"});
        rpt.print('Ejercicio Actual', {footer: true, y: rpt.currentY() + 2, align: "right"});
        rpt.print(options.fechaDesde, {footer: true, y: rpt.currentY() + 3, align: "right"});
        rpt.print(options.fechaHasta, {footer: true, y: rpt.currentY() + 4, align: "right"}); 

        rpt.print('Listado diario legal detallado.', { y: rpt.currentY() + 20, fontsize: 16, fontBold: true, align: "center"});  
        rpt.print(options.filtro, { fontsize: 10, fontBold: false, align: "center"});  
    };

    var counter = 0;
    var detailFunction = function(rpt, data) {
       counter++;
        rpt.band([
            {data: data.fecha, width: 60, align: 1},
            {data: data.cuenta, width: 80, align: 1},
            {data: data.descricuenta, width: 180, align: 1},
            {data: data.descricuentaasiento, width: 200, align: 1},
            {data: data.referencia , width: 60, align: 1},
            {data: data.debe, width: 85, align: 3},
            {data: data.haber, width: 75, align: 3}
        ], {border:0, width: 0, wrap: 1, fill: counter % 2 === 0 ? '#FFFFFF' : options.confiRep.colorInterlineado, textColor: '#000000'} );     
    };

   /* var footerFunction = function(rpt) {
       // rpt.line(rpt.currentX(), rpt.maxY(), rpt.maxX(), rpt.maxY());
        rpt.fontBold();
        rpt.fontSize(8);
        rpt.bandLine(1);
        rpt.pageNumber({text: "Página: {0} of {1}", footer: true, y: rpt.currentY()+15 , align: "right"});
        rpt.print("Fecha Impresión: "+(new Date().toLocaleDateString()), {y: rpt.currentY()+15, align: "left"});
    };*/
    
    var nameheader = function ( rpt, data ) {
        rpt.print(data.mes, {y: rpt.currentY() + 20 , fontsize: 11, fontBold: true, align: "3"});
        rpt.print("COMPROBANTE: " + data.comprobante +"-"+ data.descricom, {y: rpt.currentY()+15 , fontsize: 11, fontBold: true, align: "3"});
        if (options.confiRep.lineasCabeceras) {
        rpt.bandLine(1);
        }
        rpt.band([
            {data: 'FECHA', width: 60, align: 1},
            {data: 'CUENTA', width: 80, align: 1},
            {data: 'DESC. DE CUENTA' , width: 180, align: 1},
            {data: 'DESC. ASIENTO' , width: 200, align: 1},
            {data: 'REFERENCIA' , width: 70, align: 1},
            {data: 'DEBE', width: 75, align: 3},
            {data: 'HABER', width: 75, align: 3}
        ], {border:0, width: 0, wrap: 1, fill: options.confiRep.colorCabecera, textColor: '#000000', fontsize: 12});
        if (options.confiRep.lineasCabeceras) {
        rpt.bandLine(1);
        }

        
    };


     var sumGroupOne = function(x, r) {
         if (options.confiRep.lineasSubTotal) {
        x.bandLine(1);
        }
        x.fontBold();
        x.band([
            {data: ' Total Dia: ' + r.fecha, width: 100, align: 3},
            {data: ' Cant Doc: ' + x.totals.id, width: 390, align: 1},
            {data: x.totals.debe, width: 175, align: 3},
            {data: x.totals.haber, width: 76, align: 3}
        ], {border:0, width: 0, wrap: 1, fill: options.confiRep.colorCabecera, textColor: '#000000', fontsize: 12});
        x.fontNormal();
        if (options.confiRep.lineasSubTotal) {
        x.bandLine(1);
        }
    };

    var sumGroupTotal = function(rpt, data) {
        rpt.print("TOTAL GENERAL: ", {y: rpt.currentY()+15, align: "left"});
        rpt.standardFooter([
            ['id',1,3],
            ['debe',6,3],
            ['haber', 7, 3]
        ], {border:0, width: 0, wrap: 1, fill: options.confiRep.colorTotalGeneral, textColor: '#000000', fontsize: 14});
        if (options.confiRep.lineasTotalGeneral) {
        rpt.bandLine(1);
        }
        rpt.newline();
    };

    // You don't have to pass in a report name; it will default to "report.pdf"
    var reportName = ruta;

    var totalFormatter = function(data, callback) {
      if (data.debe) { data.debe = options.simboloMoneda +" "+ data.debe; }
      if (data.haber) { data.haber = options.simboloMoneda +" "+ data.haber; }
      callback(null, data);
    };

    var rpt = new Report(reportName, {landscape:true, paper: 'letter'});

    rpt
      .margins({left:15, top:15, bottom:15, right: 15}) 
      .pageHeader( headerFunction )
      .finalSummary( sumGroupTotal  )// Optional
      //.userdata( {hi: 1} )// Optional 
      .margins(30)
      .data(options.data)
      .sum('debe')
      .sum('haber')
      .count('id')
      .detail( detailFunction ) 
      .totalFormatter( totalFormatter ) // Optional

    rpt.groupBy( "mes" )
    rpt.groupBy( "fecha" )
      .header( nameheader )
      .sum('debe')
      .sum('haber')
      .count('id')
      .footer( sumGroupOne )

    // Debug output is always nice (Optional, to help you see the structure)
    
    rpt.printStructure();

    // This does the MAGIC...  :-)
    console.time("Rendered");
    rpt.render(function(err, name) {
        console.timeEnd("Rendered");
        callback(null, name);
    });
}

exports.dataReport = function() {
  return {
    image: 'report/formats/logo_innova.jpg',
    name: "SAMUEL OSPINA",
    company: "DISTRIBUIDORA DE SOFTWARE INNOVA ZULIA, C.A",
    rif:'J-40309595-7',
    address: "AV 8-B ENTRE CALLE 66 Y 67 CECILIO ACOSTA CASA #66A-41, SECTOR SANTA RITA",
    city: "MARACAIBO",
    state: "ZULIA",
    postal: "4001",
    filtro:"Fecha : 01/01/2016 al 30/02/2016",
    marcaAgua:"Disoinzuca",
    simboloMoneda:"$",
    horaImpresion:"Hora de impresion : 12:00pm",
    fechaDesde:"Desde: 01/01/2016",
    fechaHasta:"Hasta: 30/02/2016",
    confiRep:{
      colorCabecera:"#c0c0c0",
      colorSubTotal:"#F0F0F0",
      colorTotalGeneral:"#a8a8a8",
      colorInterlineado:"#F0F0F0",
      lineasCabeceras:false,
      lineasSubTotal:false,
      lineasTotalGeneral:false
    },
    data: [
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'DICIEMBRE-2015', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000002', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000003', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000003', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000003', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000003', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000003', mes:'ENERO-2016', fecha:'3/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'1/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000},
       {r:1, comprobante:'0000000001', mes:'FEBRERO-2016', fecha:'2/1/2016', cuenta:'1.1.01.01.001', descricuenta:'aaaaaa', descricuentaasiento:'bbbbbb', descricom:'test', referencia:'00-021558', debe:2000, haber:2000}
    ]
  }
}

exports.testreport = function(ruta, callback) {
  this.printreport(this.dataReport() , ruta, function (err, name) {
    if (err){ 
      callback(err, null)
      console.log(err)
    }
    console.log('Report Send')
    callback(null, name)
  });
}`
************************************ with this code i make a test: list_diario_legal_detallado_test.js

`var express = require('express'),
  fs = require('fs'),
  app = express();

app.get('/ldld', function (req, res) {
     var filePath = 'report/formats/ldld.pdf'
     var rep = require('./list_diario_legal_detallado.js')
     rep.testreport(filePath, function(err, name) {
   	 if (err) {
        console.log(err)
   	 }
     fs.readFile(filePath , function (err, data){
        res.contentType("application/pdf");
        res.send(data);
     });
   });
});

app.listen(3000, function(){
    console.log('Listening on 3000');
});
`

**Comment by android-sos** [comment]
Hi, i've solved the problem, this was happening because I add 15 to y: var, so erase that and this is ready to work fine.
`rpt.print("TOTAL GENERAL: ", {y: rpt.currentY()+15, align: "left"});`
Thx u.

...Take this opportunity, there is a way to add a label like a band, see this sample, I add Total Dia ti a band

` x.band([
            // {data: ' Total Dia: ' + r.fecha, width: 100, align: 3},
            {data: ' Cant Doc: ' + x.totals.id, width: 390, align: 1},`

but in this, i would like add a label 'Total Genereal'

`  rpt.standardFooter([
            ['id',1,3],
            ['debe',5,3],
            ['haber', 6, 3]
        ],`
