### ISSUE TITLE
Update pdfkit package to 0.8.0.

### ISSUE THREAD

**Issue by hillkim7** [NathanaelA/fluentreports#50]
Due to the problem that some CJK characters are not visible with current pdfkit 0.7.2, I would like to be pdfkit updated to the latest version 0.8.0 in package.json of fluentreports package.
"dependencies": {
    "pdfkit": "^0.7.2"
  },
-->
"dependencies": {
    "pdfkit": "^0.8.0"
  },

**Comment by NathanaelA** [comment]
I might have time in the next couple weeks to do this; but the main issue is that before I can do this I need to run multiple tests to make sure nothing in .8 breaks fluent reports..

**Comment by hillkim7** [comment]
I updated it to pdfkit version 0.8.0 manually. Since I have been used for a month and found nothing wrong yet.
Anyway I appreciate you for providing us nice report library.

**Comment by NathanaelA** [comment]
@hillkim7 - Awesome that is good to hear that you have had no issues running v.0.8.0 on it.   :-)
