### ISSUE TITLE
How to generate invoice and send to the front end to download it ?

### ISSUE THREAD

**Issue by chanakaDe** [NathanaelA/fluentreports#53]
My backend is NodeJS and front end is AngularJS. ERP like system.
http://www.faceinfotech.com/ReportDemo.pdf
This is the invoice in need to generate.
Specially I have a NodeJS REST API. So I need to generate and send this PDF in response call. Is that possible ?
And also do you have the example code of creating a document like invoice ?

**Comment by NathanaelA** [comment]
Yes, you can generate the pdf; and then send it as the API response.
Yep, check out the demos; one of them is an invoice.

**Comment by chanakaDe** [comment]
You mean this page : http://www.fluentreports.com/demo.html
In this page I only can see a Fax example. there's no any invoice demo. In your home page, there are some images. But no codes.
I just need to make like this. http://www.fluentreports.com/i/demo2.png or http://www.fluentreports.com/i/demo5.png. Where can I find a demo for these type of documents ?

**Comment by chanakaDe** [comment]
@NathanaelA Please provide me some links or example code. There's only one demo in your demo page.

**Comment by NathanaelA** [comment]
https://github.com/NathanaelA/fluentreports/tree/master/examples

**Comment by chanakaDe** [comment]
@NathanaelA Thanks a lot. If this works as I need, that's awesome. And I think this should work. And you are a life saver man :+1:  I tried this a lot and lot. Posted some questions here and there.
http://stackoverflow.com/questions/42584134/how-to-generate-pdf-from-dynamically-loading-data-with-angularjs
And didn't get a good response. I'm trying this now..... :+1:  will come back to you shortly
