### ISSUE TITLE
Documentation for box() is incorrect

### ISSUE THREAD

**Issue by beaudesigns** [NathanaelA/fluentreports#54]
Documentation for box indicates:

```
box ( startX, startY, endX, endY, options)
```

This led me to assume that the `endX` and `endY` options were a fixed point on the page. They appear to actually be width & height values.

It'd more correctly be:
```
box ( startX, startY, boxWidth, boxHeight, options)
```

**Comment by NathanaelA** [comment]
Documentation fixed in next version.  Thanks.
