### ISSUE TITLE
Error: target.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by snenp** [NathanaelA/fluentreports#55]
****** Error on query TypeError: target.hasOwnProperty is not a function
    at ReportGroup._expandRowTree (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:5276:28)
    at continueRendering (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:5057:22)
    at groupChangeCallback (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:5103:21)
    at ReportGroup._renderIt (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:5131:21)
    at groupContinue (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:3811:33)
    at renderData (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:3836:17)
    at ReportDataSet._renderIt (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:3967:17)
    at renderGroup (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:4105:41)
    at ReportSection._renderIt (D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:4113:13)
    at D:\EtiquetesP\node_modules\fluentreports\lib\fluentReports.js:1227:33 +67ms

**The code:**

I get the data for the report from a form.

```
router.post('/', function(req, res, next) {
	debug('****** Form Data: \n %O', req.body);
	
	var qry = new dbConfig.PW.Request();
	
	debug('****** Query Insert Eti: ',qrys.qry_insert_eti(req.body));
	qry.query(qrys.qry_insert_eti(req.body))
	.then(function(next){

		var headerFunction = function(Report) {
	        Report.print("Label", {fontSize: 22, bold: true, underline:true, align: "center"});
	        Report.newLine(2);
	    };

	    var footerFunction = function(Report) {
	        Report.line(Report.currentX(), Report.maxY()-18, Report.maxX(), Report.maxY()-18);
	        Report.pageNumber({text: "Page {0} of {1}", footer: true, align: "right"});
	        Report.print("Printed: "+(new Date().toLocaleDateString()), {y: Report.maxY()-14, align: "left"});
	    };

	    var reportdetail = function (Report,data) {
		    Report.band( [
		        {data: data.foofield1, width: 50, align: 3, zborder:{left:1, right: 1, top: 0, bottom: 1}}
		    ], {border:1, width: 0, wrap: 1} );
		};

	    var rpt = new Report("EtiquetaP2.pdf")
	        .margins(20)                            // Change the Margins to 20 pixels
	        .pageHeader(headerFunction)             // Add a header
	        .data(req.body)                           // Add our Data
	        .detail(reportdetail) 					// Put how we want to print out the data line.
	        .pageFooter(footerFunction)             // Add a footer          
	        .render();

		res.render('newEti', { title: 'Nova Etiqueta' });
	})
	.catch(function (err) { 
		debug('****** Error on query', err);
		req.body=''; 
		res.render('newEti', { title: 'Nova Etiqueta' });
	});
});

```

**Comment by NathanaelA** [comment]
It is hard to diagnose without seeing the data that was passed in, but this typically means that some part of your data is "undefined" or broken, for example something like this:
`var data = [{foofield1: 1}, {foofield1: 2}, undefined]`
might cause that issue.  The report engine was expecting a third row of data and you passed it undefined; so this means when it try `row[2].foofield1.hasOwnProperty` it will break because foofield1 is undefined...

The engine does do a lot of validations; but the engine assumes you are passing in valid data; because checking every single field in every single row in large data reports slows things down immensely.   So, the `assumption` is you are passing in correct data...  ;-)

**Comment by NathanaelA** [comment]
Closing do to inactivity.
