### ISSUE TITLE
QUESTION: Sub-Reports for account groups?

### ISSUE THREAD

**Issue by beauwest** [NathanaelA/fluentreports#58]
I'd like to add a sub-report after each group for a `.groupBy()` object. Is that possible?

```
var nameGroup = rpt.groupBy( "name" )
      .header( nameHeader )
      .footer( nameFooter );

nameGroup.addReport(subReportObject, data);
```

Based on [the code](https://github.com/NathanaelA/fluentreports/blob/be8fcd152dcf64972b9cd36e66b7942162a7acfc/lib/fluentReports.js#L563), it feels like that type of thing should work, but I haven't been successful.

**Comment by NathanaelA** [comment]
Yeah, it should work according to the source.   Not sure why it isn't.

**Comment by NathanaelA** [comment]
I have several reports that this actually does work, and the FRG depends on this functionality for its ability to work.  Can you give me a solid example that fails and I'll try and determine why.

**Comment by beauwest** [comment]
To be honest, I don't remember what the specific scenario was from 3 years ago. Going forward I'd expect to use FRG instead for the most part.
