### ISSUE TITLE
Column size 5 chars

### ISSUE THREAD

**Issue by recycleroy** [NathanaelA/fluentreports#61]
Any width < 10 for .band related operation fails . I looked in fluentreports.js modified the items I thought would allow for a smaller char cell but no luck.

Thanks

**Comment by mgetz** [comment]
recycleroy, 
How does it fail? Do you have a recreate for the issue?
Thanks.

**Comment by recycleroy** [comment]
Good morning,

I’m running node js 6.xx on linux. Using demo2.js as a template, whenever the rpt.band() function is called with a width of less than 10, the program hangs. This applies to the header as well as the detail operations.

 

Thanks,

 



Roy Moore

President

Drive Connect, LLC

2842 Broadway Center Blvd.
Brandon, FL 33510

941-371-0001 Office

941-371-0003 FAX

813-764-6785 Cell

www.drive-chat.com

**Comment by NathanaelA** [comment]
@recycleroy - This is fixed in v1.19 (soon to be released).   Thanks for the bug report and steps to duplicate.
