### ISSUE TITLE
Is there a way to integrate into React?

### ISSUE THREAD

**Issue by activebiz** [NathanaelA/fluentreports#62]
Is there a way to integrate this library into react? Any pointers.

**Comment by NathanaelA** [comment]
I don't see any reason it won't work in react.  It is just an additional library that you call when you want to generate a report.   You should be able to use it exactly as the examples show.

**Comment by activebiz** [comment]
Thanks @NathanaelA Do we need to enable server side rendering for this? Or this can work in client side SPA?

**Comment by NathanaelA** [comment]
To my knowledge it should work 100% client side perfectly fine.   I do a lot of testing currently 100% client side in browser, and no issues so far.
