### ISSUE TITLE
Question: About Padding in Band

### ISSUE THREAD

**Issue by CarlosEstevez13** [NathanaelA/fluentreports#67]
Hi
I am trying to use padding option into a band function, but it doesn't work.
This is my code:
`rpt.band([
            {data:' texto: ', width:78, border:{left:1, right: 1, top: 1, bottom: 1}, padding:1}
        ]);`

Could you tell me what it's wrong?
Thank you.

**Comment by NathanaelA** [comment]
I did find a height padding issue which is fixed in 1.1.6 -- however; the way to use padding is like so:
```
var detail = function(r, row) {
    r.fontsize(9);
    r.band([
        {data: row.favorite, width: 70, align: 'left'},
        {data: row.least, width: 70, align: 'right'}
    ],{border: 1, padding: 12});
};```

Padding is a global option that effects all fields, not just a single field.
