### ISSUE TITLE
Support for render image other ways

### ISSUE THREAD

**Issue by xypherbo** [NathanaelA/fluentreports#71]
Need some other way to print image in report. Ex. Img binary, base64, stream.

**Comment by NathanaelA** [comment]
I'm not sure what you are asking.   The report itself is a PDF; so when you embed the image inside it; you get a image in any PDF viewer.

**Comment by xypherbo** [comment]
I found that i can use buffer for Rpt.image now. then this issue can close. But its not written in the document.
