### ISSUE TITLE
Selective borders on a band

### ISSUE THREAD

**Issue by mikemadu** [NathanaelA/fluentreports#75]
Please tell me if I am missing something. A band with options property "border:1" works. But what's the syntax for using an object with top, left, right and bottom to selectively choose which part of the band that should have a visible border?

**Comment by NathanaelA** [comment]
Sorry, when I did a search of the source earlier; it was set to whole words so it skipped where it is implemented.   It is NOT implemented on the options field; it is implemented on the per-field portion.
```
band ([{data: blah, border: {left: 1, right: 1, top: 0, bottom: 0}, width: 50}, ...])
```

**Comment by mikemadu** [comment]
It is clear now. Thanks for the great work you've done and continue doing. Keep it up.
