### ISSUE TITLE
GroceryList

### ISSUE THREAD

**Issue by isauranina** [NathanaelA/fluentreports#80]
Good morning Nathanael
I need help, I could provide the code of GroceryList3.png that has fluentreports in its repository.
![grocery list](https://user-images.githubusercontent.com/15202951/46619439-1f3f3d00-caf0-11e8-903c-217cc0f9edb3.png)

**Comment by NathanaelA** [comment]
The code is part of demo6.js:
https://github.com/NathanaelA/fluentreports/blob/master/examples/demo6.js#L72
