### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by userRpt** [NathanaelA/fluentreports#81]
Hi,
is there any update on availability of  utf-8 encoding in reports ?

Thanks in advance

**Comment by NathanaelA** [comment]
I need a test report to see the issue.

**Comment by NathanaelA** [comment]
Duplicate of #65

**Comment by userRpt** [comment]
> I need a test report to see the issue.

I need croatian characters to be displayed (č,ć,š,đ)

[testRpt.pdf](https://github.com/NathanaelA/fluentreports/files/2463338/testRpt.pdf)

**Comment by userRpt** [comment]
> I need a test report to see the issue.

I need croatian characters to be displayed (č, ć, š, ž, đ)

[testRpt.pdf](https://github.com/NathanaelA/fluentreports/files/2463346/testRpt.pdf)

**Comment by NathanaelA** [comment]
@userRpt - No I meant a sample JS file for creating a report with the UTF characters.   Then I can test with it.   :grinning:

**Comment by userRpt** [comment]
Here you are :D  :

`var Report = require('fluentReports').Report;
var appConfig = require('../appLaTosConfig.js'),
    objekt = {},
    db = require('../db.js');


function kontrolniList(req, res) {
    var mydata =
        [{
            brojKontrolnogLista: "123456789",
            brojTransakcije: "TLTLTLTLTLTLT 455654546",
            proizvodNaziv: "T12 ",
            spremnikNaziv: "T12",
            skladistarNaziv: "operator operator",

            vozacPin: "10496",
            vozacIme: "Nikola Nikola",
            vozacPrezime: "Test testšššš",
            tvrtkaNaziv: "A.P. ććđđđđđđ",
            zavrsetakTransakcija: "13.12.2000., 24:24h",
            vucnoVozilo: "ŠI 228 FF",
            prikljucnoVozilo: "ŠI 888 EE",

            istocenaNekorKolicina: "123.456",
            istocenaKorKolicina: "123.123",
            srednjaTemp: "123.123",
            unesenaGustoca: "0.123456",
            izracunataMasa: "111.111",

            datumVrijemeIspisa: "12.12.2000.,   12:12h"
        },
        ];


    var pageHeader = function (rpt, mydata) {
        rpt.print(mydata.nazivFirme, { align: 2, fontBold: true });
        rpt.print(mydata.namjenaFirme, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.adresa, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.kontaktBroj, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.mailKontakt, { align: 2, fontBold: false, fontSize: 10 });
        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ])
    }
    var detail = function (rpt, mydata) {
        rpt.print("KONTROLNI LIST", { align: 2, fontBold: true, fontSize: 14, fontItalic: true });
        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "Broj kontrolnog lista:", width: 225, },
            { data: mydata.brojKontrolnogLista },
        ], { x: 50 });
        rpt.band([
            { data: "Broj transakcije:", width: 225, },
            { data: mydata.brojTransakcije },
        ], { x: 50 });
        rpt.band([
            { data: "Proizvod:", width: 225, },
            { data: mydata.proizvodNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Spremnik:", width: 225, },
            { data: mydata.spremnikNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Skladištar:", width: 225, },
            { data: mydata.skladistarNaziv },
        ], { x: 50 });

        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "ID vozača:", width: 225, },
            { data: mydata.vozacPin },
        ], { x: 50 });
        rpt.band([
            { data: "Ime vozača:", width: 225, },
            { data: mydata.vozacIme },
        ], { x: 50 });
        rpt.band([
            { data: "Prezime vozača:", width: 225, },
            { data: mydata.vozacPrezime },
        ], { x: 50 });
        rpt.band([
            { data: "Tvrtka vozača:", width: 225, },
            { data: mydata.tvrtkaNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Završetak transakcije:", width: 225, },
            { data: mydata.zavrsetakTransakcija },
        ], { x: 50 });
        rpt.band([
            { data: "Vučno vozilo:", width: 225, },
            { data: mydata.vucnoVozilo },
        ], { x: 50 });
        rpt.band([
            { data: "Priključno vozilo:", width: 225, },
            { data: mydata.prikljucnoVozilo },
        ], { x: 50 });

        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "Istočena nekorigirana količina [lit]:", width: 375, fontBold: true },
            { data: mydata.istocenaNekorKolicina, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Istočena korigirana količina [lit] na 15°C:", width: 375, fontBold: true },
            { data: mydata.istocenaKorKolicina, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Srednja temperatura [°C]:", width: 375, fontBold: true },
            { data: mydata.srednjaTemp, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Unesena gustoća [kg/l]:", width: 375, fontBold: true },
            { data: mydata.unesenaGustoca, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Izračunata masa [kg] (unes.gustoća. x korig.količina):", width: 375, fontBold: true },
            { data: mydata.izracunataMasa, fontBold: true },
        ], { x: 50 });

        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
    }

    var pageFooter = function (rpt, mydata) {

        rpt.band([
            { data: "Datum i vrijeme ispisa:", width: 375, underline: true },
            { data: "Potpis skladištara:", width: 150, underline: true },
        ], { x: 50, y: 690 });
        rpt.newline();
        rpt.band([
            { data: mydata.datumVrijemeIspisa, width: 375 },
        ], { x: 50 })

    }

    // You don't have to pass in a report name; it will default to "report.pdf"
    var reportName = "buffer";

    var rpt = new Report(reportName, ({
        font: 'myFont'
    }))
        .fontSize(12) // Optional
        .margins(30)
        .data(mydata)
        .header(pageHeader)
        .detail(detail)
        .footer(pageFooter)
        ;

    rpt.registerFont("arialunicodems", { normal: 'NodeSrv/arialunicodems.ttf', bold: 'NodeSrv/Arial-Unicode-Bold.ttf', 'italic': 'arialunicodems.ttf' })

    console.time("Rendered");
    rpt.render(function (err, name) {
        res.setHeader('Content-type', 'application/pdf');
        res.send(name);
    });
}
module.exports = objekt;
`

**Comment by userRpt** [comment]
Here you are :D : 

`var Report = require('fluentReports').Report;
var objekt = {};


function kontrolniList(req, res) {
    var mydata =
        [{
            brojKontrolnogLista: "123456789",
            brojTransakcije: "TLTLTLTLTLTLT 455654546",
            proizvodNaziv: "T12 ",
            spremnikNaziv: "T12",
            skladistarNaziv: "operator operator",

            vozacPin: "10496",
            vozacIme: "Nikola Nikola",
            vozacPrezime: "Test testšššš",
            tvrtkaNaziv: "A.P. ććđđđđđđ",
            zavrsetakTransakcija: "13.12.2000., 24:24h",
            vucnoVozilo: "ŠI 228 FF",
            prikljucnoVozilo: "ŠI 888 EE",

            istocenaNekorKolicina: "123.456",
            istocenaKorKolicina: "123.123",
            srednjaTemp: "123.123",
            unesenaGustoca: "0.123456",
            izracunataMasa: "111.111",

            datumVrijemeIspisa: "12.12.2000.,   12:12h"
        },
        ];


    var pageHeader = function (rpt, mydata) {
        rpt.print(mydata.nazivFirme, { align: 2, fontBold: true });
        rpt.print(mydata.namjenaFirme, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.adresa, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.kontaktBroj, { align: 2, fontBold: false, fontSize: 10 });
        rpt.print(mydata.mailKontakt, { align: 2, fontBold: false, fontSize: 10 });
        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ])
    }
    var detail = function (rpt, mydata) {
        rpt.print("KONTROLNI LIST", { align: 2, fontBold: true, fontSize: 14, fontItalic: true });
        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "Broj kontrolnog lista:", width: 225, },
            { data: mydata.brojKontrolnogLista },
        ], { x: 50 });
        rpt.band([
            { data: "Broj transakcije:", width: 225, },
            { data: mydata.brojTransakcije },
        ], { x: 50 });
        rpt.band([
            { data: "Proizvod:", width: 225, },
            { data: mydata.proizvodNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Spremnik:", width: 225, },
            { data: mydata.spremnikNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Skladištar:", width: 225, },
            { data: mydata.skladistarNaziv },
        ], { x: 50 });

        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "ID vozača:", width: 225, },
            { data: mydata.vozacPin },
        ], { x: 50 });
        rpt.band([
            { data: "Ime vozača:", width: 225, },
            { data: mydata.vozacIme },
        ], { x: 50 });
        rpt.band([
            { data: "Prezime vozača:", width: 225, },
            { data: mydata.vozacPrezime },
        ], { x: 50 });
        rpt.band([
            { data: "Tvrtka vozača:", width: 225, },
            { data: mydata.tvrtkaNaziv },
        ], { x: 50 });
        rpt.band([
            { data: "Završetak transakcije:", width: 225, },
            { data: mydata.zavrsetakTransakcija },
        ], { x: 50 });
        rpt.band([
            { data: "Vučno vozilo:", width: 225, },
            { data: mydata.vucnoVozilo },
        ], { x: 50 });
        rpt.band([
            { data: "Priključno vozilo:", width: 225, },
            { data: mydata.prikljucnoVozilo },
        ], { x: 50 });

        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
        rpt.newline();

        rpt.band([
            { data: "Istočena nekorigirana količina [lit]:", width: 375, fontBold: true },
            { data: mydata.istocenaNekorKolicina, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Istočena korigirana količina [lit] na 15°C:", width: 375, fontBold: true },
            { data: mydata.istocenaKorKolicina, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Srednja temperatura [°C]:", width: 375, fontBold: true },
            { data: mydata.srednjaTemp, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Unesena gustoća [kg/l]:", width: 375, fontBold: true },
            { data: mydata.unesenaGustoca, fontBold: true },
        ], { x: 50 });
        rpt.band([
            { data: "Izračunata masa [kg] (unes.gustoća. x korig.količina):", width: 375, fontBold: true },
            { data: mydata.izracunataMasa, fontBold: true },
        ], { x: 50 });


        rpt.newline();
        rpt.band([
            { data: " ", width: 550, border: { left: 0, right: 0, top: 1, bottom: 0 } },
        ]);
    }

    var pageFooter = function (rpt, mydata) {

        rpt.band([
            { data: "Datum i vrijeme ispisa:", width: 375, underline: true },
            { data: "Potpis skladištara:", width: 150, underline: true },
        ], { x: 50, y: 690 });
        rpt.newline();
        rpt.band([
            { data: mydata.datumVrijemeIspisa, width: 375 },
        ], { x: 50 })

    }


    // You don't have to pass in a report name; it will default to "report.pdf"
    var reportName = "buffer";

    var rpt = new Report(reportName, ({
        font: 'myFont'
    }))
        .fontSize(12) // Optional
        .margins(30)
        .data(mydata)
        .header(pageHeader)
        .detail(detail)
        .footer(pageFooter)
        ;

    rpt.registerFont("arialunicodems", { normal: 'NodeSrv/arialunicodems.ttf', bold: 'NodeSrv/Arial-Unicode-Bold.ttf', 'italic': 'arialunicodems.ttf' })

    console.time("Rendered");
    rpt.render(function (err, name) {
        res.setHeader('Content-type', 'application/pdf');
        res.send(name);
    });

}


module.exports = objekt;
`
