### ISSUE TITLE
Unclear on how to use this module within a NodeJS Express Server

### ISSUE THREAD

**Issue by zipzit** [NathanaelA/fluentreports#89]
Apologies if I'm asking the wrong question, or just doing this wrong.  I was hoping to use tool as a report generator from a NodeJS Express server.  

e.g. user clicks on link, get request goes to server, report is generated and returned.  

$ `npm install fluentreports --save ` 

in code...

```
var Report = require('fluentreports');

router.get('/report', function (req, res, next) {
    var data = [{ name: 'Elijah', age: 18 }, { name: 'Abraham', age: 22 }, { name: 'Gavin', age: 28 }];
    // Create a Report  
    var rpt = new Report("Report.pdf")
        .pageHeader(["Employee Ages"])      // Add a simple (optional) page Header...        
        .data(data)	 			 	      // Add some Data (This is required)
        .detail([['name', 200], ['age', 50]]) // Layout the report in a Grid of 200px & 50px
        .render();  				          // Render the Report (required if you want output...)
   // res.render(rpt);    // not sure this will work. Stop debugger here and see what's there.
})

```
There doesn't appear to be any module definition for this package.  Is that correct?  I see 
`(typeof exports === 'undefined' ? this : exports));` at the bottom of the library lib/fluentReports.js .   Not sure whats up with that. I was expecting a simple module declaration. 

I will say when this package is simply present in my local node_modules directory (and with all references to any reporting, remarked out), my entire site fails with` cannot get /` . Sigh. 

Is this intended as either a browser client only tool?  Or perhaps a javascript stand alone tool intended for desktop use?  Apologies if I'm just doing it wrong.

**Comment by zipzit** [comment]
Okay, figured it out, with hints from [this posting... ](https://stackoverflow.com/questions/44467522/using-fluentreports-to-add-multiple-tables) . Success!

`const Report = require('fluentreports').Report;`

```
router.get('/report', function (req, res, next) {

    var data = [{ name: 'Elijah', age: 18 }, { name: 'Abraham', age: 22 }, { name: 'Gavin', age: 28 }];
    // Create a Report  
    var rpt = new Report(res)              // note the response ("res")
        .pageHeader(["Employee Ages"])     // Add a simple (optional) page Header...        
        .data(data)	 			 	       // Add some Data (This is required)
        .detail([['name', 200], ['age', 50]]) // Layout the report in a Grid of 200px & 50px
        .render();  	
})
```

Recommendation: Add these above lines of code to a file.txt called "NodeJS Express Simple How To Example.txt" in the examples folder (or just include it in the Readme)

Many thanks to Nathanael for all the work done here...

**Comment by NathanaelA** [comment]
I am glad you got it working.  For anyone seeing this issue in the future -- the reporting engine can work both on Server (NodeJS) and Client (Browser), it is totally up to you where you want to run it.
