### ISSUE TITLE
Overlapping Final Summary and Page Footer

### ISSUE THREAD

**Issue by jhen913** [Nathanaela/fluentreports#9]
I am encountering an issue wherein the final summary overlaps with the page footer. I just want the page footer to be always at the bottom of the page so I set a specific y-coordinate, but sometimes this happens. I cannot upload a sample PDF as it is not supported here. Here is my code instead:

	var Report = require('fluentreports').Report;

	function constructReport() {
	"use strict";

	var orderItems = [
		{number: 1, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet, consectetur adipisicing el", quantity: 1, amount: 100, common: 1},
		{number: 2, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet, consectetur adipisicing el", quantity: 1, amount: 100, common: 1},
		{number: 3, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet, consectetur adipisicing el", quantity: 1, amount: 100, common: 1},
		{number: 4, description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum Lorem ipsum dolor sit amet, consectetur adipisicing el", quantity: 1, amount: 100, common: 1}
	];

	var pageHeader = function(report, data) {
		report.fontSize(14);
		report.setCurrentY(50);

		//Company Name, INVOICE
		report.band([
			{data: "Best Products, Inc.", width: 270, fontBold: true},
			{data: "INVOICE", align: 3, width: 260, fontBold: true}
		], {border: 0, wrap: 1}); 

		report.fontSize(10);

		//Company Address, Invoice Date
		report.band([
			{data: "#35", width: 270},
			{data: "12/01/2013", align: 3, width: 260}
		], {border: 0, wrap: 1}); 

		report.band([
			{data: "City, State Zip Code", width: 270},
			{data: "Invoice #001", align: 3, width: 260}
		], {border: 0, wrap: 1}); 

		report.band([
			{data: "85-23923-3102923", width: 270},
			{data: "12345", align: 3, width: 260}
		], {border: 0, wrap: 1}); 

		report.band([
			{data: "1232193210-01", width: 530},
		], {border: 0, wrap: 1}); 

		report.newLine(5);
	}

	var detailBondBody = function(report, data) {
		report.fontSize(11);

  		report.band([
  					{data: data.number, width: 50, align: 2},
  					{data: data.description, width: 300},
  					{data: data.quantity, width: 60},
  					{data: data.amount, width: 120}], {border: 0, width: 0, wrap: 1});
	};

	var pageFooter = function(report, data) {
		//report.newLine(); 

		report.print("Invoice #001", {width: 530, y: 720, align: "right"});
		report.print("Company slogan here!", {width: 530, align: "right"});

		//report.newLine();
	}

	var finalSummary = function(report, data) {
		report.newLine();

		report.band([
  					{data: "", width: 350},
  					{data: "Subtotal", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});

		report.band([
  					{data: "", width: 350},
  					{data: "Taxable", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});

		report.band([
  					{data: "", width: 350},
  					{data: "Tax Rate", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});

		report.band([
  					{data: "", width: 350},
  					{data: "Tax Due", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});

		report.band([
  					{data: "", width: 350},
  					{data: "Other", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});

		report.band([
  					{data: "", width: 350},
  					{data: "Total Due", width: 60},
  					{data: "1000", width: 120}], {border: 0, width: 0, wrap: 1});
	}

	var report = new Report("issue_overlapping.pdf", {paper: "letter"});
	report.pageHeader(pageHeader)
		  .data(orderItems)
		  .detail(detailBondBody)
		  .pageFooter(pageFooter)
		  .margins(40);

	report.groupBy("common")
		  .footer(finalSummary);

	report.printStructure();

	var pdf = report.render(function(err, name) {
      	if (err) {
        	console.error("Report had an error: ", err);
      	} else {
        	console.log("Filename: ", name);
      	}
  	});
	}

	var rpt = constructReport();

I hope you can help me with this. Thank you!

**Comment by Nathanaela** [comment]
Wooooo Hoooooooo....    This is now fixed in v1.00
