### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by tasca** [NathanaelA/fluentreports#90]
I have this eror on install fluentreports:

tasca@tasca-PC:~/app$ npm i fluentreports
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/KellPro/pdfkit.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tasca/.npm/_logs/2019-05-13T20_14_49_440Z-debug.log
16 silly resolveWithNewModule fluentreports@1.2.3 checking installable status
17 silly fetchPackageMetaData error for pdfkit@github:KellPro/pdfkit Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/KellPro/pdfkit.$
17 silly fetchPackageMetaData

how can I solve ?

**Comment by NathanaelA** [comment]
Sorry, looks like the package file is messed up.  I'll be releasing a new version shortly.

**Comment by NathanaelA** [comment]
v1.2.4 has been pushed that fixes this issue.
