### ISSUE TITLE
Confusing Instructions -- .detail function and alignment

### ISSUE THREAD

**Issue by zipzit** [NathanaelA/fluentreports#91]
The [fluentreports documentation ](http://www.fluentreports.com/docs.html)for the `detail()` function clearly state: 

> .detail ( detailOutput )
> Description
> This is used so that the report system know how to output each detail record. This is used in most reports; but in some you might not need it.
> 
> Parameters
> detailOutput - this can be a array, a string or a function
> array = [[Data Key, Data Width, Data Alignment],[...],...] Key is the key of the data to use for output, width is how wide to make this, alignment is right, (left), or center.
> 

Unfortunately, there is no obvious description on how to use alignment, left, right or center.  Using text values ('left', 'center') = big dog fail. Object declarations fail, too.

Turns out you need to use constants: 1, 2 or 3.  (see below, lines 3727 in fluentReports.js file)

Perhaps the documentation could be updated to assist others in the future on this detail?  

As a mininum: 

> Examples
> MyReportObject.detail([["name", 120, 1], ["address", 200, 2], ["state", 20, 2]]);  // 1=align left, 2 = align center
> or
> MyReportObject.detail("{{name}} lives in the state of {{state}}");
> 

Or in the alternative could the constants be defined in "global" scope?

Not sure where else those constants are used, perhaps should just be spelled out in the documentation.  Apologies if that guidance is in the documentation and I just missed it...

[Code base ](https://github.com/NathanaelA/fluentreports/blob/master/lib/fluentReports.js#L3727) shows:
```
 // CONSTANTS
        left: 1,
        right: 3,
        center: 2,
        /** @constant
         * @desc Aligns the Text on the Left */
        LEFT: 1,
        /** @constant
         * @desc Aligns the Text on the Right */
        RIGHT: 3,
        /** @constant
         * @desc Centers the Text */
        CENTER: 2
```

Don't mean to be ungrateful.  Albeit initially a bit confusing to understand, this is a pretty handy library.  Many thanks to Nathanael and supporters for their work here.  

I will say, the lesson on chaining the report functions via [this posting](https://stackoverflow.com/questions/44467522/using-fluentreports-to-add-multiple-tables) got me pretty far.  

Again, many thanks to the team for this product...

**Comment by NathanaelA** [comment]
Good idea on updating the docs; I know their are holes in the docs...  Thanks for letting me know about this one...  :D

**Comment by NathanaelA** [comment]
Ah, I fixed the bug; actually anywhere alignment can be set it is supposed to support both the text and number version.   One of these days we will depreciate this support; but right now the idea is that either is supported.  :grinning:
