### ISSUE TITLE
Update to PDFKit .9

### ISSUE THREAD

**Issue by NathanaelA** [NathanaelA/fluentreports#92]
PDFKit .9 has some changes in the internals...   So this will require some changes in the dependencies, some changes in requires and a lot of testing.

**Comment by beaudesigns** [comment]
PDFKit v0.10.0 came out June 2019.

**Comment by NathanaelA** [comment]
PDFKit v0.11.0 Came out  Jan 2020   --  Is this something Kellpro needs or wants me to upgrade the engine to.  #135 would be fixed by using the latest version as the linebreaker class handles the newline (and other) characters properly.

**Comment by NathanaelA** [comment]
Updated to v0.11.0
