### ISSUE TITLE
Unable to get totalFormatter to function

### ISSUE THREAD

**Issue by zipzit** [NathanaelA/fluentreports#93]
Not sure what's going on here.. 

Somehow some of my numerical data displays as 43.00000000003.  Sure would like to fix that.   

```
           var myTotalFormatter = function (data, callback) {
                console.log("myTotalFormatter: ", data)
                for (var key in data) { 
                    if (data.hasOwnProperty(key)) {
                        if (key === 'total') {
                            data[key] = '$ ' + data[key].toFixed(2);
                         }
                    }
                }
                callback(null, data);
            };

            // Create a Report  
            var rpt = new Report(res, options)              // note the response ("res")
                .pageHeader(headerFunction)     // Add a simple (optional) page Header...        
                .data(artData)	 			 	       // Add some Data (This is required)
                .detail([ ['BWshade$', dataWidth, alg],['sleeve$', dataWidth, alg],
                              ['cash$', dataWidth, alg], ['credit$', dataWidth, alg], ['total', dataWidth, alg] ])
                .totalFormatter(myTotalFormatter)

            // Chain a second report for totals
            var rpt2 = new Report(rpt, ({ isSibling: true }))
                .margins(40)
                .data(summaryData)               // Add some Data (This is required) 
                .pageHeader(headerFunction2)
                . .detail([ ['BWshade$', dataWidth, alg],['sleeve$', dataWidth, alg],
                              ['cash$', dataWidth, alg], ['credit$', dataWidth, alg], ['total', dataWidth, alg] ])
                .totalFormatter(myTotalFormatter)
                .render();
        })
```

I've been wading thru the examples, and this isn't all that helpful:

```
var totalFormatter = function(data, callback) {
   // if (data.hours) { data.hours = ': ' + data.hours; }
    callback(null, data);
  };
```

My artData and summaryData are arrays of objects.  Actually summaryData is an array with a single object inside.  I've tried all combinations I can think of, but the `console.log` is a fail.  The problem is, when `myTotalFormatter()` function gets called the data sent there looks like an empty Object class..

![image](https://user-images.githubusercontent.com/4413134/57724318-60c43780-763f-11e9-95f2-f450f8740996.png)

I did play around with `data.forEach(function (dataObj) {...` thinking the info being passed from one chained function to the next was an array of objects .  No go..  I did some testing involving the order the chained functions were called.. No go.

Anybody have a simple intuitive example of formatter in use?

Many thanks to Nathanael & team for their work on this project . 

![image](https://user-images.githubusercontent.com/4413134/57724268-42f6d280-763f-11e9-8326-9713aa637ee2.png)

Suggestions:
Add survey of users on http://www.fluentreports.com/ website.   How are people using this product?  Browser use?  Server Use? What type of server setup?
What content are they generating?    The big pareto bars probably need simple examples.  100% of the folks I surveyed are using node / express / spreadsheet style output, but then my sample size is pretty small... just me :^)

Promisify all functions? That sure makes it easy to see whats getting passed between the chained functions .

**Comment by NathanaelA** [comment]
1. Can you copy the full report here w/ data; and I'll take a look.  It is always easier to see the issue if I can run the report locally.  :-)   
2. Making it use promises would require a bit of reworking; the whole engine supports async data access; so most of it is callbacks for a reason (i.e. some of the callbacks can be called out of order w/o their being any issues, like the data retrieval).        Parts of it could be turned into promises pretty easily; but if I was to spend the time on working on the engine that way; I think I would rather get typings into play.

**Comment by zipzit** [comment]
I could have sworn I submitted this comment a few hours ago.  

Here is my fix on the raw data just before it goes to the Report() function...

```
/**
 * Clean up all the dollar entries for output report.
 * Input format is [{}] (an array of objects)
 * Remember, Javascript passes object/array's by 'reference'
 * ref: //https://gomakethings.com/the-es6-way-to-loop-through-objects-with-vanilla-javascript/
 * Reminder, the JS toFixed() function returns a string.  
 */
function cleanUpReport$$Data(ArrayOfObjects) { 
    ArrayOfObjects.forEach(function (dataObj) {
        Object.keys(dataObj).forEach(function(key) {  
            if (dataObj.hasOwnProperty(key)) {
                if ((key === 'cash$') || (key === 'commision$') || (key === 'credit$') || (key === 'total')) {
                    dataObj[key] = '$ ' + dataObj[key].toFixed(2); 
                }
            }
        })
    })
};
```

I'd rather not submit the actual data.  Its for a customer. The column headers names give it away. The one thing about promises, its easy to see EXACTLY what is being passed down the .then() chain...  But I do understand the reluctance to go there . If you are going to go to promises, you might as well go all the way to Async / Await functionality.  I get it . 

Not to worry. There's not much to do here.  I don't understand how the data in the report chain is structured.  If its [{},{},{},{}] then the function above is handy. 

Again, don't mean to be ungrateful. Without this library, I'd still be trying to figure out how to create a point of sale Z-tape for the customer...   Again, thx.

**Comment by NathanaelA** [comment]
Please feel free to totally modify the data, just leave it in the same layout as you are using...   All I really need a few of the dollar values that cause the issues.   :-)    I would like to see if it is something you are doing wrong, or something I messed up on.    :grinning: 

The report engine was majorily overhauled a while back and some of the lesser used features might have an issue that needs to be changed.   I do have a pretty decent number of test reports here; but I noticed not a single one actually used the report total function.   So I do have a gap in my testing for that area...     So I do need to create another report for that...

As for the promises; I happen to like promises and async/await.    Just none of the tech was ready when I first wrote the engine, and the promise libraries that did exist were very slow compared to callbacks.   When you have 1000's of lines of data streaming on a server from a database to generate a 30-50 page report -- you notice the speed...    

I would really love to simplify the engine with Await/Async/Promises now --- as it takes even me a couple hours to wrap my head around what it is doing in some spots, as the callback hell is quite a pita...   ;-)     

I'll see what I can do about a survey; not a bad idea.   :-)

**Comment by NathanaelA** [comment]
I'm not sure how I missed this before but my demo2.js has a working totalFormatter; 
If I comment out the line the report shows this:
![image](https://user-images.githubusercontent.com/850871/78466910-41555380-76c4-11ea-9c72-70d01b6144b7.png)

If I let the totalFormatter run it shows this:
![image](https://user-images.githubusercontent.com/850871/78466917-57fbaa80-76c4-11ea-9fcb-e3da09d57e8f.png)

As you can see their is a huge difference in the report when using the totalFormatter so it is obviously running...

---
Now as to your report; the totalFormater is only used for the totals system; you have no totals...  :)
You can have the system create totals per record group and for all records printed...   The report asumes

So if you wanted to use it; you should do your report like this:
```
const runTotals = function(rpt) {
        rpt.standardFooter([
            ['BWshade$',1,3],
            ['sleeve$', 2, 3],
            ['cash$', 3, 3],
            ['credit$', 4, 3],
            ['total', 5, 3],
        ]);
    };

    const detail = function(rpt, data) {
        rpt.band([
            {data: data['BWshade$'], width: 100},
            {data: data['sleeve$'], width: 100},
            {data: data['cash$'], width: 100},
            {data: data['credit$'], width: 100},
            // RAW Unformatted Data
            {data: data['total'], width: 100},
            // Instead we can format the data to look correctly!
            {data: data['total'].toFixed(2), width: 100},
            ], {border: 1});
    };


const resultReport = new Report(rptName)
        .data(artData)	 			 	       
        .pageFooter(runTotals)
        .detail(detail)
        .sum('BWshade$')
        .sum('sleeve$')
        .sum('cash$')
        .sum('credit$')
        .sum('total')
        .totalFormatter(myTotalFormatter);

```

So then the system is creating sums for your records; and then when it pages; it prints the footer with all the totals.  Which looks like this;

![image](https://user-images.githubusercontent.com/850871/78467333-d65a4b80-76c8-11ea-96bb-bd9b7cce673c.png)

**Comment by zipzit** [comment]
145.170000000000 ?

**Comment by NathanaelA** [comment]
@zipzit - If you see the code above:

```
            // RAW Unformatted Data
            {data: data['total'], width: 100},
            // Instead we can format the data to look correctly!
            {data: data['total'].toFixed(2), width: 100},
```
Column 5 I outputted the data AS-IS; raw just like your original code did -- (to show that I set the value to be something large: `145.17000000002` -- gotta love floats in JS).   In Column 6 I outputted it as toFixed.  So it shows 145.17, and Then the totals line I used your totalFormatter so it was formatted to `$1008.93`    Basically was trying to show you how to easily fix your report...  :-)
