### ISSUE TITLE
Confusing Documentation? Report.X

### ISSUE THREAD

**Issue by zipzit** [NathanaelA/fluentreports#94]
Documentation for Report.x is way confusing.  

![image](https://user-images.githubusercontent.com/4413134/58912577-3f4eec80-86cf-11e9-9b05-b8cd84c53dd3.png)

[Documentation is here...](http://www.fluentreports.com/docs.html)

I'm trying to figure out how to show header once and only once.  My report extends over multiple pages, but when it does so, there are duplicate and incorrect headers displayed in odd places.  My customer is impatient, and I can't waste more time on this stuff.  I believe that displaying the header once and only once would preclude the dilemma.  

Report.x -- Huh? What is this?  
constants .show --> once - Show the header/footer only once .  Yup, this is what I want to try.  

Oh. awesome, there is an example for the Report.x part of the documentation. That will make it totally clear.  er, wait.  

> Example:
> var MyReportObject = new Report("MyCoolReport.pdf", {autoPrint: true});
> Would create the report called "MyCoolReport.pdf" and auto print it when it is opened in a pdf reader.

What the heck does that even mean?  Possible that example is for another paragraph of documention? It certainly doesn't fit here.  Apologies if I'm doing this wrong.

**Comment by NathanaelA** [comment]
Sorry, I'm always open for PR's.  :grinning:    Doc's are not always my strong point.  :grinning:

`Report.x` meant functions and/or constants accessible from Report class.    I.e. `Report.show.once` is a constant usable in your report...   So that is why the example is their; it is part of the `Report` class information.   However you are correct, it might be better placed above the `report.x` section...  And thinking about it maybe report.x should be changed to `Report Constants and Functions`

Now as to headers; maybe you should try looking at the example reports or the example reports w/ editor on the fluentreports site.  ;-)

But specifically if all you want is a single header `.titleHeader ( headerOutput, options )` printed only on the first page...

**Comment by FredBesterwitch** [comment]
> Documentation for Report.x is way confusing.
> 
> ![image](https://user-images.githubusercontent.com/4413134/58912577-3f4eec80-86cf-11e9-9b05-b8cd84c53dd3.png)
> 
> [Documentation is here...](http://www.fluentreports.com/docs.html)
> 
> I'm trying to figure out how to show header once and only once. My report extends over multiple pages, but when it does so, there are duplicate and incorrect headers displayed in odd places. My customer is impatient, and I can't waste more time on this stuff. I believe that displaying the header once and only once would preclude the dilemma.
> 
> Report.x -- Huh? What is this? constants .show --> once - Show the header/footer only once . Yup, this is what I want to try.
> 
> Oh. awesome, there is an example for the Report.x part of the documentation. That will make it totally clear. er, wait.
> 
> > Example:
> > var MyReportObject = new Report("MyCoolReport.pdf", {autoPrint: true});
> > Would create the report called "MyCoolReport.pdf" and auto print it when it is opened in a pdf reader.
> 
> What the heck does that even mean? Possible that example is for another paragraph of documention? It certainly doesn't fit here. Apologies if I'm doing this wrong.

Hi, Did you manage to solve this issue, I have the same requirement, I only want to print the group header once .
Documentation Says in groupby options you can show.once, but not clear as to what property we are setting.

is it groupBy("invoice_number",{show: 0}) or groupBy("invoice_number",0) or groupBy("invoice_number",Report.show.once)?

I tried all no luck, the group header prints on every page

**Comment by FredBesterwitch** [comment]
Ok, Found it 
the below setting will only print group header once
.groupBy("invoice_number",{runHeader: 0})

for newPageOnly 
.groupBy("invoice_number",{runHeader: 1})

always
.groupBy("invoice_number",{runHeader: 2})

@NathanaelA  thanks you for a great product
